import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaLibSql } from '@prisma/adapter-libsql';

const adapterConfig = {
  url: process.env.DATABASE_URL!, // This is the local dev DB
};
const adapter = new PrismaLibSql(adapterConfig);

const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Starting seed...');
  // Clear existing data (optional, for a clean slate each time)
  await prisma.itemMovimentacao_saida.deleteMany({});
  await prisma.itemMovimentacao_entrada.deleteMany({});
  await prisma.saidaEstoque.deleteMany({});
  await prisma.entradaEstoque.deleteMany({});
  await prisma.produto.deleteMany({});
  await prisma.fornecedor.deleteMany({});
  await prisma.gasto.deleteMany({});
  await prisma.funcionario.deleteMany({});

  // Seed fornecedores
  const fornecedoresData = [
    {
      id: 'f1',
      razaoSocial: 'Robert Bosch Ltda',
      nomeFantasia: 'Bosch',
      cnpj: '45.990.181/0001-89',
      inscricaoEstadual: '123.456.789.123',
      contato: 'João Silva',
      telefone: '(11) 4166-8000',
      email: 'comercial@bosch.com.br',
      enderecoLogradouro: 'Via Anhanguera',
      enderecoNumero: 'Km 98',
      enderecoComplemento: 'Galpão 1',
      enderecoBairro: 'Distrito Industrial',
      enderecoCidade: 'Campinas',
      enderecoEstado: 'SP',
      enderecoCep: '13065-900',
      dadosBancariosBanco: 'Itaú',
      dadosBancariosAgencia: '1234',
      dadosBancariosConta: '56789-0',
      dadosBancariosTipoConta: 'Corrente',
      condicaoPagamentoPadrao: '30/60/90',
      prazoEntrega: 7,
      avaliacao: 5,
      observacoes: 'Fornecedor premium. Entrega sempre no prazo.',
      createdAt: new Date('2024-01-15'),
    },
    {
      id: 'f2',
      razaoSocial: 'NGK do Brasil Ltda',
      nomeFantasia: 'NGK',
      cnpj: '47.384.984/0001-01',
      inscricaoEstadual: '456.789.123.456',
      contato: 'Maria Santos',
      telefone: '(11) 2165-8900',
      email: 'vendas@ngk.com.br',
      enderecoLogradouro: 'Av. Piraporinha',
      enderecoNumero: '1950',
      enderecoComplemento: '',
      enderecoBairro: 'Diadema',
      enderecoCidade: 'São Paulo',
      enderecoEstado: 'SP',
      enderecoCep: '09950-000',
      dadosBancariosBanco: 'Bradesco',
      dadosBancariosAgencia: '2345',
      dadosBancariosConta: '67890-1',
      dadosBancariosTipoConta: 'Corrente',
      condicaoPagamentoPadrao: '30 dias',
      prazoEntrega: 5,
      avaliacao: 5,
      observacoes: 'Especialista em velas e sensores.',
      createdAt: new Date('2024-02-10'),
    },
    {
      id: 'f3',
      razaoSocial: 'Cofap Amortecedores S/A',
      nomeFantasia: 'Cofap',
      cnpj: '60.476.884/0001-52',
      inscricaoEstadual: '789.123.456.789',
      contato: 'Carlos Oliveira',
      telefone: '(11) 3388-5700',
      email: 'comercial@cofap.com.br',
      enderecoLogradouro: 'Av. Industrial',
      enderecoNumero: '600',
      enderecoComplemento: 'Bloco B',
      enderecoBairro: 'Santo André',
      enderecoCidade: 'São Paulo',
      enderecoEstado: 'SP',
      enderecoCep: '09080-500',
      dadosBancariosBanco: 'Santander',
      dadosBancariosAgencia: '3456',
      dadosBancariosConta: '78901-2',
      dadosBancariosTipoConta: 'Corrente',
      condicaoPagamentoPadrao: '28 dias',
      prazoEntrega: 10,
      avaliacao: 4,
      observacoes: 'Líder em suspensão e amortecedores.',
      createdAt: new Date('2024-01-20'),
    },
    {
      id: 'f4',
      razaoSocial: 'Mahle Metal Leve S/A',
      nomeFantasia: 'Mahle',
      cnpj: '60.894.730/0001-05',
      inscricaoEstadual: '321.654.987.321',
      contato: 'Ana Pereira',
      telefone: '(47) 3451-6000',
      email: 'vendas@mahle.com.br',
      enderecoLogradouro: 'Rod. BR-280',
      enderecoNumero: 'Km 50',
      enderecoComplemento: '',
      enderecoBairro: 'Zona Industrial',
      enderecoCidade: 'Jaraguá do Sul',
      enderecoEstado: 'SC',
      enderecoCep: '89256-900',
      dadosBancariosBanco: 'Banco do Brasil',
      dadosBancariosAgencia: '4567',
      dadosBancariosConta: '89012-3',
      dadosBancariosTipoConta: 'Corrente',
      condicaoPagamentoPadrao: '30/60',
      prazoEntrega: 8,
      avaliacao: 5,
      observacoes: 'Especialista em filtros e pistões.',
      createdAt: new Date('2024-03-05'),
    },
    {
      id: 'f5',
      razaoSocial: 'Monroe Amortecedores Ltda',
      nomeFantasia: 'Monroe',
      cnpj: '61.089.062/0001-90',
      inscricaoEstadual: '654.987.321.654',
      contato: 'Roberto Costa',
      telefone: '(11) 4040-5000',
      email: 'pedidos@monroe.com.br',
      enderecoLogradouro: 'Av. das Indústrias',
      enderecoNumero: '2200',
      enderecoComplemento: 'Galpão 3',
      enderecoBairro: 'Guarulhos',
      enderecoCidade: 'São Paulo',
      enderecoEstado: 'SP',
      enderecoCep: '07220-000',
      dadosBancariosBanco: 'Caixa',
      dadosBancariosAgencia: '5678',
      dadosBancariosConta: '90123-4',
      dadosBancariosTipoConta: 'Corrente',
      condicaoPagamentoPadrao: '30 dias',
      prazoEntrega: 6,
      avaliacao: 4,
      observacoes: 'Excelente qualidade em amortecedores.',
      createdAt: new Date('2024-02-25'),
    },
  ];

  for (const f of fornecedoresData) {
    await prisma.fornecedor.create({
      data: f,
    });
  }
  console.log(`Seeded ${fornecedoresData.length} fornecedores.`);

  // Seed produtos
  const produtosData = [
    {
      id: 'p1',
      nome: 'Filtro de Óleo Honda Civic',
      slug: 'filtro-oleo-honda-civic',
      sku: 'FO-HON-001',
      codigoOEM: '15400-PLM-A01',
      codigoBarras: '7891234567890',
      ncm: '84212300',
      cest: '0107800',
      referenciaCruzada: JSON.stringify(['PH6017A', 'W610/6']),
      marca: 'Mahle',
      fabricanteOriginal: 'Honda',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Filtros',
      subcategoria: 'Filtro de Óleo',
      tags: JSON.stringify(['filtro', 'óleo', 'lubrificação', 'motor']),
      localizacaoEstoque: 'Prateleira A3 - Caixa 12',
      setorAlmoxarifado: 'Setor A',
      pesoBruto: 0.35,
      pesoLiquido: 0.3,
      comprimento: 8,
      largura: 8,
      altura: 10,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Metal e papel filtrante',
      cor: 'Preto',
      garantia: '6 meses de fábrica',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 18.5,
      freteEntrada: 1.2,
      impostosEntrada: 2.3,
      custoTotal: 22,
      margemLucro: 45,
      precoVendaSugerido: 31.9,
      precoVendaBalcao: 34.9,
      precoB2B: 28.9,
      precoMinimo: 26,
      descontoMaximo: 15,
      precoSite: 32.9,
      precoPromocional: 29.9,
      dataInicioPromocao: new Date('2024-04-01'),
      dataFimPromocao: new Date('2024-04-30'),
      exibirNoSite: true,
      destaqueHome: true,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 45,
      estoqueMinimo: 10,
      estoqueMaximo: 100,
      estoqueSeguranca: 15,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f4',
      prazoReposicao: 5,
      fotos: JSON.stringify(['/produtos/filtro-oleo-1.jpg']),
      imagemPrincipal: '/produtos/filtro-oleo-1.jpg',
      descricaoCurta: 'Filtro de óleo de alta qualidade para Honda Civic. Filtragem eficiente e durabilidade garantida.',
      descricaoCompleta: 'O Filtro de Óleo Mahle para Honda Civic oferece filtragem de alta eficiência, removendo partículas e impurezas do óleo do motor. Fabricado com materiais de primeira qualidade, garante proteção máxima ao motor do seu veículo.',
      caracteristicas: JSON.stringify(['Filtragem de alta eficiência', 'Material resistente à corrosão', 'Válvula anti-retorno integrada', 'Compatível com óleos sintéticos']),
      videoUrl: '',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-04-10'),
    },
    {
      id: 'p2',
      nome: 'Pastilha de Freio Dianteira VW Golf',
      slug: 'pastilha-freio-dianteira-vw-golf',
      sku: 'PF-VW-002',
      codigoOEM: '1K0698151',
      codigoBarras: '7891234567891',
      ncm: '68131000',
      cest: '0109900',
      referenciaCruzada: JSON.stringify(['BP1108', 'P85073']),
      marca: 'Bosch',
      fabricanteOriginal: 'Volkswagen',
      paisOrigem: 'Alemanha',
      tipoAplicacao: 'especifico',
      tipoPeca: 'original',
      categoria: 'Freios',
      subcategoria: 'Pastilhas',
      tags: JSON.stringify(['freio', 'pastilha', 'dianteiro', 'segurança']),
      localizacaoEstoque: 'Prateleira B2 - Caixa 08',
      setorAlmoxarifado: 'Setor B',
      pesoBruto: 1.2,
      pesoLiquido: 0.95,
      comprimento: 15,
      largura: 12,
      altura: 5,
      unidadeMedida: 'KIT',
      conteudoEmbalagem: 4,
      material: 'Cerâmica',
      cor: 'Cinza',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 145,
      freteEntrada: 8.5,
      impostosEntrada: 18,
      custoTotal: 171.5,
      margemLucro: 40,
      precoVendaSugerido: 240.1,
      precoVendaBalcao: 259.9,
      precoB2B: 219.9,
      precoMinimo: 199.9,
      descontoMaximo: 10,
      precoSite: 249.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: true,
      aliquotaICMS: 18,
      aliquotaIPI: 8,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 28,
      estoqueMinimo: 5,
      estoqueMaximo: 50,
      estoqueSeguranca: 8,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 7,
      fotos: JSON.stringify(['/produtos/pastilha-freio-1.jpg']),
      imagemPrincipal: '/produtos/pastilha-freio-1.jpg',
      descricaoCurta: 'Kit de pastilhas de freio dianteiras Bosch para VW Golf, Jetta e Audi A3. Frenagem segura e silenciosa.',
      descricaoCompleta: 'As Pastilhas de Freio Bosch são desenvolvidas com tecnologia de ponta, oferecendo frenagem precisa e silenciosa. Composição cerâmica que garante menor desgaste dos discos e maior vida útil do sistema de freios.',
      caracteristicas: JSON.stringify(['Tecnologia cerâmica QuietCast', 'Baixa geração de pó', 'Indicador de desgaste', 'Calços anti-ruído inclusos']),
      videoUrl: '',
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-04-08'),
    },
    {
      id: 'p3',
      nome: 'Amortecedor Dianteiro Fiat Strada',
      slug: 'amortecedor-dianteiro-fiat-strada',
      sku: 'AM-FIA-003',
      codigoOEM: '51925198',
      codigoBarras: '7891234567892',
      ncm: '87083000',
      cest: '0107100',
      referenciaCruzada: JSON.stringify(['41901', 'GP32860']),
      marca: 'Cofap',
      fabricanteOriginal: 'Fiat',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Suspensão',
      subcategoria: 'Amortecedores',
      tags: JSON.stringify(['amortecedor', 'suspensão', 'dianteiro', 'conforto']),
      localizacaoEstoque: 'Prateleira C1 - Caixa 01',
      setorAlmoxarifado: 'Setor C',
      pesoBruto: 4.5,
      pesoLiquido: 4.2,
      comprimento: 50,
      largura: 12,
      altura: 12,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Aço e borracha',
      cor: 'Preto/Amarelo',
      garantia: '12 meses ou 20.000 km',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 185,
      freteEntrada: 12,
      impostosEntrada: 22,
      custoTotal: 219,
      margemLucro: 35,
      precoVendaSugerido: 295.65,
      precoVendaBalcao: 319.9,
      precoB2B: 279.9,
      precoMinimo: 259.9,
      descontoMaximo: 12,
      precoSite: 309.9,
      precoPromocional: 289.9,
      dataInicioPromocao: new Date('2024-04-05'),
      dataFimPromocao: new Date('2024-04-20'),
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 10,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 12,
      estoqueMinimo: 4,
      estoqueMaximo: 30,
      estoqueSeguranca: 6,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f3',
      prazoReposicao: 10,
      fotos: JSON.stringify(['/produtos/amortecedor-1.jpg']),
      imagemPrincipal: '/produtos/amortecedor-1.jpg',
      descricaoCurta: 'Amortecedor dianteiro Cofap Turbogas para Fiat Strada e Palio Weekend. Conforto e estabilidade.',
      descricaoCompleta: 'O Amortecedor Cofap Turbogas oferece tecnologia de ponta com pressurização de gás nitrogênio, proporcionando resposta mais rápida e precisa da suspensão. Ideal para uso urbano e estradas.',
      caracteristicas: JSON.stringify(['Tecnologia Turbogas', 'Pressurização a gás nitrogênio', 'Maior estabilidade em curvas', 'Redução de fadiga do motorista']),
      videoUrl: '',
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-04-05'),
    },
    {
      id: 'p4',
      nome: 'Vela de Ignição NGK Iridium',
      slug: 'vela-ignicao-ngk-iridium',
      sku: 'VE-NGK-004',
      codigoOEM: 'ILZKR7B11',
      codigoBarras: '7891234567893',
      ncm: '85111000',
      cest: '0108900',
      referenciaCruzada: JSON.stringify(['ZXE16HR11', 'IK16TT']),
      marca: 'NGK',
      fabricanteOriginal: '',
      paisOrigem: 'Japão',
      tipoAplicacao: 'universal',
      tipoPeca: 'original',
      categoria: 'Elétrica',
      subcategoria: 'Velas de Ignição',
      tags: JSON.stringify(['vela', 'ignição', 'iridium', 'performance']),
      localizacaoEstoque: 'Prateleira D4 - Caixa 22',
      setorAlmoxarifado: 'Setor D',
      pesoBruto: 0.08,
      pesoLiquido: 0.06,
      comprimento: 3,
      largura: 2,
      altura: 8,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Irídio e platina',
      cor: 'Prata',
      garantia: '24 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 48,
      freteEntrada: 2,
      impostosEntrada: 6,
      custoTotal: 56,
      margemLucro: 50,
      precoVendaSugerido: 84,
      precoVendaBalcao: 89.9,
      precoB2B: 74.9,
      precoMinimo: 68,
      descontoMaximo: 10,
      precoSite: 84.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: true,
      aliquotaICMS: 18,
      aliquotaIPI: 12,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 120,
      estoqueMinimo: 20,
      estoqueMaximo: 200,
      estoqueSeguranca: 30,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f2',
      prazoReposicao: 5,
      fotos: JSON.stringify(['/produtos/vela-ngk-1.jpg']),
      imagemPrincipal: '/produtos/vela-ngk-1.jpg',
      descricaoCurta: 'Vela de ignição NGK Iridium de alta performance. Maior durabilidade e eficiência na combustão.',
      descricaoCompleta: 'A Vela de Ignição NGK Iridium é a escolha premium para motores modernos. O eletrodo central de irídio ultrafino proporciona uma faísca mais potente e consistente, resultando em melhor partida, maior economia de combustível e menor emissão de poluentes.',
      caracteristicas: JSON.stringify(['Eletrodo central de irídio', 'Durabilidade 4x maior que velas convencionais', 'Melhora partida a frio', 'Economia de combustível de até 5%']),
      videoUrl: '',
      createdAt: new Date('2024-01-25'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p5',
      nome: 'Correia Dentada Gates PowerGrip',
      slug: 'correia-dentada-gates-powergrip',
      sku: 'CO-GAT-005',
      codigoOEM: '5544XS',
      codigoBarras: '7891234567894',
      ncm: '40103900',
      cest: '0100100',
      referenciaCruzada: JSON.stringify(['CT909', 'TB909K1']),
      marca: 'Gates',
      fabricanteOriginal: '',
      paisOrigem: 'EUA',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Correia e Corrente',
      subcategoria: 'Correias Dentadas',
      tags: JSON.stringify(['correia', 'dentada', 'sincronismo', 'motor']),
      localizacaoEstoque: 'Prateleira E2 - Caixa 15',
      setorAlmoxarifado: 'Setor E',
      pesoBruto: 0.25,
      pesoLiquido: 0.2,
      comprimento: 30,
      largura: 3,
      altura: 3,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Borracha reforçada com fibra de vidro',
      cor: 'Preto',
      garantia: '24 meses ou 40.000 km',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 85,
      freteEntrada: 5,
      impostosEntrada: 10,
      custoTotal: 100,
      margemLucro: 45,
      precoVendaSugerido: 145,
      precoVendaBalcao: 159.9,
      precoB2B: 139.9,
      precoMinimo: 125,
      descontoMaximo: 15,
      precoSite: 149.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 35,
      estoqueMinimo: 8,
      estoqueMaximo: 60,
      estoqueSeguranca: 12,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 7,
      fotos: JSON.stringify(['/produtos/correia-1.jpg']),
      imagemPrincipal: '/produtos/correia-1.jpg',
      descricaoCurta: 'Correia dentada Gates PowerGrip para VW Gol e Fox. Sincronismo perfeito e longa durabilidade.',
      descricaoCompleta: 'A Correia Dentada Gates PowerGrip é fabricada com materiais de alta tecnologia que garantem resistência ao desgaste, ao calor e à tração. Mantém o sincronismo perfeito do motor, essencial para o funcionamento correto do veículo.',
      caracteristicas: JSON.stringify(['Tecnologia PowerGrip', 'Fibra de vidro de alta resistência', 'Resistente a óleo e calor', 'Troca recomendada a cada 60.000 km']),
      videoUrl: '',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-03-28'),
    },
    {
      id: 'p6',
      nome: 'Bomba de Água GM Chevrolet Onix',
      slug: 'bomba-agua-gm-onix',
      sku: 'BA-GM-006',
      codigoOEM: '24579450',
      codigoBarras: '7891234567895',
      ncm: '84137030',
      cest: '0108200',
      referenciaCruzada: JSON.stringify(['FBA0854', 'P981']),
      marca: 'Indisa',
      fabricanteOriginal: 'GM',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Arrefecimento',
      subcategoria: 'Bombas de Água',
      tags: JSON.stringify(['bomba', 'água', 'arrefecimento', 'motor']),
      localizacaoEstoque: 'Prateleira F3 - Caixa 09',
      setorAlmoxarifado: 'Setor F',
      pesoBruto: 1.8,
      pesoLiquido: 1.5,
      comprimento: 15,
      largura: 12,
      altura: 10,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Alumínio e aço',
      cor: 'Alumínio natural',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 125,
      freteEntrada: 8,
      impostosEntrada: 15,
      custoTotal: 148,
      margemLucro: 40,
      precoVendaSugerido: 207.2,
      precoVendaBalcao: 229.9,
      precoB2B: 199.9,
      precoMinimo: 179.9,
      descontoMaximo: 12,
      precoSite: 219.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 8,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 18,
      estoqueMinimo: 5,
      estoqueMaximo: 40,
      estoqueSeguranca: 8,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 8,
      fotos: JSON.stringify(['/produtos/bomba-agua-1.jpg']),
      imagemPrincipal: '/produtos/bomba-agua-1.jpg',
      descricaoCurta: 'Bomba de água para GM Onix e Prisma. Circulação eficiente do líquido de arrefecimento.',
      descricaoCompleta: 'A Bomba de Água Indisa para Chevrolet Onix e Prisma é fabricada com componentes de alta qualidade, garantindo a circulação eficiente do líquido de arrefecimento e protegendo o motor contra superaquecimento.',
      caracteristicas: JSON.stringify(['Rotor de alta eficiência', 'Rolamento selado de longa vida', 'Junta inclusa na embalagem', 'Testada em bancada']),
      videoUrl: '',
      createdAt: new Date('2024-02-15'),
      updatedAt: new Date('2024-03-20'),
    },
    {
      id: 'p7',
      nome: 'Kit Embreagem Sachs Fiat Uno',
      slug: 'kit-embreagem-sachs-fiat-uno',
      sku: 'EM-SAC-007',
      codigoOEM: '55190716',
      codigoBarras: '7891234567896',
      ncm: '87089990',
      cest: '0107600',
      referenciaCruzada: JSON.stringify(['K1947', '3000951003']),
      marca: 'Sachs',
      fabricanteOriginal: 'Fiat',
      paisOrigem: 'Alemanha',
      tipoAplicacao: 'especifico',
      tipoPeca: 'original',
      categoria: 'Embreagem',
      subcategoria: 'Kit Completo',
      tags: JSON.stringify(['embreagem', 'platô', 'disco', 'rolamento']),
      localizacaoEstoque: 'Prateleira G1 - Caixa 03',
      setorAlmoxarifado: 'Setor G',
      pesoBruto: 5.5,
      pesoLiquido: 5,
      comprimento: 30,
      largura: 30,
      altura: 15,
      unidadeMedida: 'KIT',
      conteudoEmbalagem: 3,
      material: 'Aço, ferro fundido e material orgânico',
      cor: 'Preto/Prata',
      garantia: '12 meses sem limite de km',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 420,
      freteEntrada: 25,
      impostosEntrada: 50,
      custoTotal: 495,
      margemLucro: 35,
      precoVendaSugerido: 668.25,
      precoVendaBalcao: 699.9,
      precoB2B: 629.9,
      precoMinimo: 589.9,
      descontoMaximo: 10,
      precoSite: 679.9,
      precoPromocional: 649.9,
      dataInicioPromocao: new Date('2024-04-10'),
      dataFimPromocao: new Date('2024-04-25'),
      exibirNoSite: true,
      destaqueHome: true,
      aliquotaICMS: 18,
      aliquotaIPI: 10,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 8,
      estoqueMinimo: 3,
      estoqueMaximo: 20,
      estoqueSeguranca: 5,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 12,
      fotos: JSON.stringify(['/produtos/kit-embreagem-1.jpg']),
      imagemPrincipal: '/produtos/kit-embreagem-1.jpg',
      descricaoCurta: 'Kit de embreagem completo Sachs para Fiat Uno e Palio. Inclui platô, disco e rolamento.',
      descricaoCompleta: 'O Kit de Embreagem Sachs é fornecedor original das principais montadoras e oferece o conjunto completo para troca: platô, disco e rolamento. Fabricado com materiais de alta qualidade para garantir durabilidade e performance.',
      caracteristicas: JSON.stringify(['Kit completo (platô + disco + rolamento)', 'Mesma especificação original de fábrica', 'Engrenamento suave e preciso', 'Maior vida útil']),
      videoUrl: '',
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-04-10'),
    },
    {
      id: 'p8',
      nome: 'Farol Dianteiro Esquerdo Toyota Corolla',
      slug: 'farol-dianteiro-esquerdo-toyota-corolla',
      sku: 'FA-TOY-008',
      codigoOEM: '81150-02B50',
      codigoBarras: '7891234567897',
      ncm: '85122010',
      cest: '0109100',
      referenciaCruzada: JSON.stringify(['TY708L', 'HO2502139']),
      marca: 'Fitam',
      fabricanteOriginal: 'Toyota',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Iluminação',
      subcategoria: 'Faróis',
      tags: JSON.stringify(['farol', 'iluminação', 'dianteiro', 'esquerdo']),
      localizacaoEstoque: 'Prateleira H2 - Caixa 01',
      setorAlmoxarifado: 'Setor H',
      pesoBruto: 3.2,
      pesoLiquido: 2.8,
      comprimento: 50,
      largura: 35,
      altura: 25,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Plástico ABS e policarbonato',
      cor: 'Preto',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 380,
      freteEntrada: 22,
      impostosEntrada: 45,
      custoTotal: 447,
      margemLucro: 38,
      precoVendaSugerido: 616.86,
      precoVendaBalcao: 649.9,
      precoB2B: 579.9,
      precoMinimo: 539.9,
      descontoMaximo: 10,
      precoSite: 629.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 8,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 6,
      estoqueMinimo: 2,
      estoqueMaximo: 15,
      estoqueSeguranca: 3,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 15,
      fotos: JSON.stringify(['/produtos/farol-corolla-1.jpg']),
      imagemPrincipal: '/produtos/farol-corolla-1.jpg',
      descricaoCurta: 'Farol dianteiro esquerdo para Toyota Corolla 2015-2019. Encaixe perfeito e alta qualidade.',
      descricaoCompleta: 'O Farol Dianteiro Fitam para Toyota Corolla é fabricado seguindo as especificações originais, garantindo encaixe perfeito e iluminação adequada. Lente em policarbonato resistente a impactos e UV.',
      caracteristicas: JSON.stringify(['Encaixe original de fábrica', 'Lente em policarbonato UV-resistente', 'Refletor de alta eficiência', 'Não inclui lâmpadas']),
      videoUrl: '',
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-04-02'),
    },
    {
      id: 'p9',
      nome: 'Sensor de Rotação VW Polo',
      slug: 'sensor-rotacao-vw-polo',
      sku: 'SE-VW-009',
      codigoOEM: '030906433K',
      codigoBarras: '7891234567898',
      ncm: '90318090',
      cest: '0110100',
      referenciaCruzada: JSON.stringify(['V10-72-1050', '0986280408']),
      marca: 'Bosch',
      fabricanteOriginal: 'Volkswagen',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'original',
      categoria: 'Elétrica',
      subcategoria: 'Sensores',
      tags: JSON.stringify(['sensor', 'rotação', 'injeção', 'eletrônica']),
      localizacaoEstoque: 'Prateleira D2 - Caixa 18',
      setorAlmoxarifado: 'Setor D',
      pesoBruto: 0.15,
      pesoLiquido: 0.12,
      comprimento: 8,
      largura: 3,
      altura: 3,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Plástico e metal',
      cor: 'Preto',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 145,
      freteEntrada: 5,
      impostosEntrada: 18,
      custoTotal: 168,
      margemLucro: 42,
      precoVendaSugerido: 238.56,
      precoVendaBalcao: 259.9,
      precoB2B: 229.9,
      precoMinimo: 209.9,
      descontoMaximo: 10,
      precoSite: 249.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 15,
      estoqueMinimo: 4,
      estoqueMaximo: 30,
      estoqueSeguranca: 6,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 7,
      fotos: JSON.stringify(['/produtos/sensor-rotacao-1.jpg']),
      imagemPrincipal: '/produtos/sensor-rotacao-1.jpg',
      descricaoCurta: 'Sensor de rotação Bosch para VW Polo e Virtus. Precisão e confiabilidade na leitura.',
      descricaoCompleta: 'O Sensor de Rotação Bosch monitora a velocidade e posição do virabrequim, enviando informações precisas à central eletrônica do motor. Essencial para o funcionamento correto do sistema de injeção e ignição.',
      caracteristicas: JSON.stringify(['Fornecedor original VW', 'Alta precisão de leitura', 'Resistente a temperaturas extremas', 'Conector original']),
      videoUrl: '',
      createdAt: new Date('2024-03-05'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p10',
      nome: 'Óleo Motor 5W30 Sintético 1L',
      slug: 'oleo-motor-5w30-sintetico-1l',
      sku: 'OL-MOB-010',
      codigoOEM: '',
      codigoBarras: '7891234567899',
      ncm: '27101932',
      cest: '0601100',
      referenciaCruzada: JSON.stringify(['Shell HX8', 'Castrol GTX']),
      marca: 'Mobil',
      fabricanteOriginal: '',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'universal',
      tipoPeca: 'original',
      categoria: 'Lubrificantes',
      subcategoria: 'Óleos de Motor',
      tags: JSON.stringify(['óleo', 'motor', 'sintético', '5w30', 'lubrificante']),
      localizacaoEstoque: 'Prateleira I1 - Caixa 01',
      setorAlmoxarifado: 'Setor I',
      pesoBruto: 1,
      pesoLiquido: 0.9,
      comprimento: 8,
      largura: 8,
      altura: 20,
      unidadeMedida: 'LT',
      conteudoEmbalagem: 1,
      material: 'Óleo sintético',
      cor: 'Âmbar',
      garantia: 'Validade 5 anos',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 32,
      freteEntrada: 2,
      impostosEntrada: 4,
      custoTotal: 38,
      margemLucro: 35,
      precoVendaSugerido: 51.3,
      precoVendaBalcao: 54.9,
      precoB2B: 47.9,
      precoMinimo: 44.9,
      descontoMaximo: 10,
      precoSite: 52.9,
      precoPromocional: 49.9,
      dataInicioPromocao: new Date('2024-04-01'),
      dataFimPromocao: new Date('2024-04-30'),
      exibirNoSite: true,
      destaqueHome: true,
      aliquotaICMS: 25,
      aliquotaIPI: 0,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 85,
      estoqueMinimo: 20,
      estoqueMaximo: 150,
      estoqueSeguranca: 30,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 3,
      fotos: JSON.stringify(['/produtos/oleo-motor-1.jpg']),
      imagemPrincipal: '/produtos/oleo-motor-1.jpg',
      descricaoCurta: 'Óleo de motor Mobil 1 5W30 totalmente sintético. Proteção máxima para seu motor.',
      descricaoCompleta: 'O Mobil 1 5W30 é um óleo de motor totalmente sintético que oferece proteção excepcional contra desgaste, depósitos e lamas. Ideal para motores modernos que exigem óleos de baixa viscosidade para melhor economia de combustível.',
      caracteristicas: JSON.stringify(['100% sintético', 'Proteção contra desgaste', 'Melhora economia de combustível', 'Partida a frio facilitada']),
      videoUrl: '',
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p11',
      nome: 'Bico Injetor Flex Ford Ka',
      slug: 'bico-injetor-flex-ford-ka',
      sku: 'BI-FOR-011',
      codigoOEM: '0280158127',
      codigoBarras: '7891234567900',
      ncm: '84099190',
      cest: '0108100',
      referenciaCruzada: JSON.stringify(['IWP143', 'FJ10629']),
      marca: 'Bosch',
      fabricanteOriginal: 'Ford',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'original',
      categoria: 'Combustível',
      subcategoria: 'Bicos Injetores',
      tags: JSON.stringify(['bico', 'injetor', 'combustível', 'flex']),
      localizacaoEstoque: 'Prateleira D5 - Caixa 11',
      setorAlmoxarifado: 'Setor D',
      pesoBruto: 0.08,
      pesoLiquido: 0.06,
      comprimento: 6,
      largura: 2,
      altura: 2,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Metal e plástico',
      cor: 'Preto/Prata',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 165,
      freteEntrada: 5,
      impostosEntrada: 20,
      custoTotal: 190,
      margemLucro: 40,
      precoVendaSugerido: 266,
      precoVendaBalcao: 289.9,
      precoB2B: 259.9,
      precoMinimo: 239.9,
      descontoMaximo: 10,
      precoSite: 279.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 8,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 22,
      estoqueMinimo: 6,
      estoqueMaximo: 40,
      estoqueSeguranca: 10,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 7,
      fotos: JSON.stringify(['/produtos/bico-injetor-1.jpg']),
      imagemPrincipal: '/produtos/bico-injetor-1.jpg',
      descricaoCurta: 'Bico injetor Bosch para Ford Ka e Ecosport Flex. Pulverização precisa do combustível.',
      descricaoCompleta: 'O Bico Injetor Bosch é projetado para sistemas flex, operando com gasolina ou etanol. Oferece pulverização precisa do combustível, garantindo melhor queima e economia.',
      caracteristicas: JSON.stringify(['Compatível com etanol e gasolina', 'Pulverização em cone', 'Alta durabilidade', 'Resistente a partículas']),
      videoUrl: '',
      createdAt: new Date('2024-03-12'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p12',
      nome: 'Terminal de Direção Renault Sandero',
      slug: 'terminal-direcao-renault-sandero',
      sku: 'TD-REN-012',
      codigoOEM: '485203446R',
      codigoBarras: '7891234567901',
      ncm: '87089490',
      cest: '0107200',
      referenciaCruzada: JSON.stringify(['JTE1116', 'TA2505']),
      marca: 'TRW',
      fabricanteOriginal: 'Renault',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Direção',
      subcategoria: 'Terminais',
      tags: JSON.stringify(['terminal', 'direção', 'articulação', 'esterçamento']),
      localizacaoEstoque: 'Prateleira J2 - Caixa 07',
      setorAlmoxarifado: 'Setor J',
      pesoBruto: 0.45,
      pesoLiquido: 0.4,
      comprimento: 15,
      largura: 5,
      altura: 5,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Aço forjado',
      cor: 'Preto',
      garantia: '12 meses ou 20.000 km',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 48,
      freteEntrada: 3,
      impostosEntrada: 6,
      custoTotal: 57,
      margemLucro: 45,
      precoVendaSugerido: 82.65,
      precoVendaBalcao: 89.9,
      precoB2B: 79.9,
      precoMinimo: 72.9,
      descontoMaximo: 12,
      precoSite: 85.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 32,
      estoqueMinimo: 8,
      estoqueMaximo: 50,
      estoqueSeguranca: 12,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 6,
      fotos: JSON.stringify(['/produtos/terminal-direcao-1.jpg']),
      imagemPrincipal: '/produtos/terminal-direcao-1.jpg',
      descricaoCurta: 'Terminal de direção TRW para Renault Sandero e Logan. Articulação suave e durável.',
      descricaoCompleta: 'O Terminal de Direção TRW é fabricado em aço forjado de alta resistência, com junta esférica de movimentação suave. Essencial para a precisão do sistema de direção.',
      caracteristicas: JSON.stringify(['Aço forjado de alta resistência', 'Junta esférica de precisão', 'Guarda-pó de borracha incluso', 'Parafuso e porca de fixação inclusos']),
      videoUrl: '',
      createdAt: new Date('2024-03-15'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p13',
      nome: 'Disco de Freio Dianteiro Hyundai HB20',
      slug: 'disco-freio-dianteiro-hyundai-hb20',
      sku: 'DF-HYU-013',
      codigoOEM: '51712-1S000',
      codigoBarras: '7891234567902',
      ncm: '87083010',
      cest: '0107300',
      referenciaCruzada: JSON.stringify(['BD4902', 'DF4426']),
      marca: 'Fremax',
      fabricanteOriginal: 'Hyundai',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Freios',
      subcategoria: 'Discos',
      tags: JSON.stringify(['disco', 'freio', 'dianteiro', 'frenagem']),
      localizacaoEstoque: 'Prateleira B3 - Caixa 02',
      setorAlmoxarifado: 'Setor B',
      pesoBruto: 6.5,
      pesoLiquido: 6.2,
      comprimento: 28,
      largura: 28,
      altura: 5,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Ferro fundido',
      cor: 'Cinza',
      garantia: '12 meses ou 20.000 km',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 78,
      freteEntrada: 8,
      impostosEntrada: 10,
      custoTotal: 96,
      margemLucro: 40,
      precoVendaSugerido: 134.4,
      precoVendaBalcao: 149.9,
      precoB2B: 129.9,
      precoMinimo: 119.9,
      descontoMaximo: 12,
      precoSite: 139.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 8,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 14,
      estoqueMinimo: 4,
      estoqueMaximo: 30,
      estoqueSeguranca: 6,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 8,
      fotos: JSON.stringify(['/produtos/disco-freio-1.jpg']),
      imagemPrincipal: '/produtos/disco-freio-1.jpg',
      descricaoCurta: 'Disco de freio dianteiro Fremax para Hyundai HB20. Ventilado para melhor dissipação de calor.',
      descricaoCompleta: 'O Disco de Freio Fremax é fabricado em ferro fundido de alta qualidade, com pista de frenagem usinada com precisão. Design ventilado que proporciona melhor dissipação de calor durante a frenagem.',
      caracteristicas: JSON.stringify(['Disco ventilado', 'Ferro fundido de alta qualidade', 'Balanceamento de fábrica', 'Tratamento anticorrosivo']),
      videoUrl: '',
      createdAt: new Date('2024-03-18'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p14',
      nome: 'Filtro de Ar Condicionado Universal',
      slug: 'filtro-ar-condicionado-universal',
      sku: 'FA-UNI-014',
      codigoOEM: '',
      codigoBarras: '7891234567903',
      ncm: '84212100',
      cest: '0107900',
      referenciaCruzada: JSON.stringify(['CU1827', 'LAK83']),
      marca: 'Mann Filter',
      fabricanteOriginal: '',
      paisOrigem: 'Alemanha',
      tipoAplicacao: 'universal',
      tipoPeca: 'paralela',
      categoria: 'Filtros',
      subcategoria: 'Filtro de Ar Condicionado',
      tags: JSON.stringify(['filtro', 'cabine', 'ar condicionado', 'pólen']),
      localizacaoEstoque: 'Prateleira A4 - Caixa 20',
      setorAlmoxarifado: 'Setor A',
      pesoBruto: 0.35,
      pesoLiquido: 0.3,
      comprimento: 25,
      largura: 20,
      altura: 3,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Material sintético',
      cor: 'Branco',
      garantia: '6 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 42,
      freteEntrada: 3,
      impostosEntrada: 5,
      custoTotal: 50,
      margemLucro: 50,
      precoVendaSugerido: 75,
      precoVendaBalcao: 79.9,
      precoB2B: 69.9,
      precoMinimo: 62.9,
      descontoMaximo: 15,
      precoSite: 74.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 48,
      estoqueMinimo: 15,
      estoqueMaximo: 80,
      estoqueSeguranca: 20,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f4',
      prazoReposicao: 5,
      fotos: JSON.stringify(['/produtos/filtro-cabine-1.jpg']),
      imagemPrincipal: '/produtos/filtro-cabine-1.jpg',
      descricaoCurta: 'Filtro de ar condicionado Mann Filter com carvão ativado. Purifica o ar da cabine.',
      descricaoCompleta: 'O Filtro de Ar Condicionado Mann Filter com carvão ativado remove pólen, poeira, bactérias e odores desagradáveis do ar que entra na cabine. Proporciona um ambiente mais saudável para os ocupantes.',
      caracteristicas: JSON.stringify(['Carvão ativado', 'Retenção de partículas finas', 'Eliminação de odores', 'Troca recomendada a cada 15.000 km']),
      videoUrl: '',
      createdAt: new Date('2024-03-20'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p15',
      nome: 'Radiador de Água Fiat Toro',
      slug: 'radiador-agua-fiat-toro',
      sku: 'RA-FIA-015',
      codigoOEM: '52049155',
      codigoBarras: '7891234567904',
      ncm: '87089100',
      cest: '0108300',
      referenciaCruzada: JSON.stringify(['RV3285', 'PA66-GF30']),
      marca: 'Visconde',
      fabricanteOriginal: 'Fiat',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Arrefecimento',
      subcategoria: 'Radiadores',
      tags: JSON.stringify(['radiador', 'arrefecimento', 'água', 'motor']),
      localizacaoEstoque: 'Prateleira F1 - Caixa 01',
      setorAlmoxarifado: 'Setor F',
      pesoBruto: 8.5,
      pesoLiquido: 7.8,
      comprimento: 70,
      largura: 50,
      altura: 5,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Alumínio e plástico',
      cor: 'Preto/Alumínio',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 580,
      freteEntrada: 35,
      impostosEntrada: 70,
      custoTotal: 685,
      margemLucro: 30,
      precoVendaSugerido: 890.5,
      precoVendaBalcao: 949.9,
      precoB2B: 849.9,
      precoMinimo: 799.9,
      descontoMaximo: 8,
      precoSite: 919.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 10,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 4,
      estoqueMinimo: 2,
      estoqueMaximo: 10,
      estoqueSeguranca: 3,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 15,
      fotos: JSON.stringify(['/produtos/radiador-1.jpg']),
      imagemPrincipal: '/produtos/radiador-1.jpg',
      descricaoCurta: 'Radiador de água Visconde para Fiat Toro. Alta capacidade de dissipação térmica.',
      descricaoCompleta: 'O Radiador Visconde para Fiat Toro é fabricado com núcleo de alumínio brazado de alta eficiência e tanques em plástico de engenharia resistente a altas temperaturas. Garante troca térmica superior e longa vida útil.',
      caracteristicas: JSON.stringify(['Núcleo de alumínio brazado', 'Tanques em plástico PA66-GF30', 'Alta capacidade de dissipação', 'Testado sob pressão']),
      videoUrl: '',
      createdAt: new Date('2024-03-22'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p16',
      nome: 'Pivô de Suspensão Inferior Chevrolet S10',
      slug: 'pivo-suspensao-inferior-chevrolet-s10',
      sku: 'PI-GM-016',
      codigoOEM: '94728557',
      codigoBarras: '7891234567905',
      ncm: '87089390',
      cest: '0107100',
      referenciaCruzada: JSON.stringify(['0220-0049', 'K80566']),
      marca: 'Nakata',
      fabricanteOriginal: 'Chevrolet',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Suspensão',
      subcategoria: 'Pivôs',
      tags: JSON.stringify(['pivô', 'suspensão', 'inferior', 'articulação']),
      localizacaoEstoque: 'Prateleira C3 - Caixa 05',
      setorAlmoxarifado: 'Setor C',
      pesoBruto: 1.2,
      pesoLiquido: 1,
      comprimento: 20,
      largura: 8,
      altura: 8,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Aço forjado',
      cor: 'Preto',
      garantia: '12 meses ou 20.000 km',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 95,
      freteEntrada: 6,
      impostosEntrada: 12,
      custoTotal: 113,
      margemLucro: 42,
      precoVendaSugerido: 160.46,
      precoVendaBalcao: 179.9,
      precoB2B: 159.9,
      precoMinimo: 145.9,
      descontoMaximo: 10,
      precoSite: 169.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 10,
      estoqueMinimo: 3,
      estoqueMaximo: 20,
      estoqueSeguranca: 5,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f3',
      prazoReposicao: 10,
      fotos: JSON.stringify(['/produtos/pivo-1.jpg']),
      imagemPrincipal: '/produtos/pivo-1.jpg',
      descricaoCurta: 'Pivô de suspensão inferior Nakata para S10 e Trailblazer. Resistente para uso severo.',
      descricaoCompleta: 'O Pivô de Suspensão Nakata é fabricado em aço forjado de alta resistência, ideal para veículos utilitários e pick-ups. Junta esférica com guarda-pó de borracha para proteção contra contaminantes.',
      caracteristicas: JSON.stringify(['Aço forjado de alta resistência', 'Para uso em condições severas', 'Guarda-pó premium', 'Graxeiro para manutenção']),
      videoUrl: '',
      createdAt: new Date('2024-03-25'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p17',
      nome: 'Bateria Automotiva 60Ah Moura',
      slug: 'bateria-automotiva-60ah-moura',
      sku: 'BA-MOU-017',
      codigoOEM: 'M60GD',
      codigoBarras: '7891234567906',
      ncm: '85071000',
      cest: '0900100',
      referenciaCruzada: JSON.stringify(['LB60DD', 'EFB60']),
      marca: 'Moura',
      fabricanteOriginal: '',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'universal',
      tipoPeca: 'original',
      categoria: 'Elétrica',
      subcategoria: 'Baterias',
      tags: JSON.stringify(['bateria', 'elétrica', '60ah', 'partida']),
      localizacaoEstoque: 'Prateleira K1 - Chão',
      setorAlmoxarifado: 'Setor K',
      pesoBruto: 16.5,
      pesoLiquido: 15,
      comprimento: 24,
      largura: 17,
      altura: 18,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Chumbo-ácido',
      cor: 'Preto/Laranja',
      garantia: '18 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 320,
      freteEntrada: 15,
      impostosEntrada: 40,
      custoTotal: 375,
      margemLucro: 25,
      precoVendaSugerido: 468.75,
      precoVendaBalcao: 499.9,
      precoB2B: 449.9,
      precoMinimo: 429.9,
      descontoMaximo: 8,
      precoSite: 479.9,
      precoPromocional: 459.9,
      dataInicioPromocao: new Date('2024-04-01'),
      dataFimPromocao: new Date('2024-04-15'),
      exibirNoSite: true,
      destaqueHome: true,
      aliquotaICMS: 18,
      aliquotaIPI: 0,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 12,
      estoqueMinimo: 4,
      estoqueMaximo: 25,
      estoqueSeguranca: 6,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 5,
      fotos: JSON.stringify(['/produtos/bateria-1.jpg']),
      imagemPrincipal: '/produtos/bateria-1.jpg',
      descricaoCurta: 'Bateria automotiva Moura 60Ah. Alta capacidade de partida e durabilidade.',
      descricaoCompleta: 'A Bateria Moura 60Ah é líder no mercado brasileiro, oferecendo alta capacidade de partida mesmo em condições extremas. Tecnologia selada livre de manutenção com indicador de carga.',
      caracteristicas: JSON.stringify(['Selada livre de manutenção', 'Indicador de carga', 'Alta capacidade de partida a frio', 'Caixa sucateada: R$ 50,00 de bônus']),
      videoUrl: '',
      createdAt: new Date('2024-03-28'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p18',
      nome: 'Palheta Limpador Parabrisa Par',
      slug: 'palheta-limpador-parabrisa-par',
      sku: 'PA-BOS-018',
      codigoOEM: '',
      codigoBarras: '7891234567907',
      ncm: '85129090',
      cest: '0109500',
      referenciaCruzada: JSON.stringify(['AP24U/AP18U', '3397007523']),
      marca: 'Bosch',
      fabricanteOriginal: '',
      paisOrigem: 'Alemanha',
      tipoAplicacao: 'universal',
      tipoPeca: 'original',
      categoria: 'Acessórios',
      subcategoria: 'Limpadores',
      tags: JSON.stringify(['palheta', 'limpador', 'parabrisa', 'borracha']),
      localizacaoEstoque: 'Prateleira L2 - Caixa 12',
      setorAlmoxarifado: 'Setor L',
      pesoBruto: 0.35,
      pesoLiquido: 0.3,
      comprimento: 60,
      largura: 5,
      altura: 3,
      unidadeMedida: 'PAR',
      conteudoEmbalagem: 2,
      material: 'Plástico e borracha',
      cor: 'Preto',
      garantia: '6 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 58,
      freteEntrada: 4,
      impostosEntrada: 7,
      custoTotal: 69,
      margemLucro: 40,
      precoVendaSugerido: 96.6,
      precoVendaBalcao: 109.9,
      precoB2B: 94.9,
      precoMinimo: 86.9,
      descontoMaximo: 12,
      precoSite: 99.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 35,
      estoqueMinimo: 10,
      estoqueMaximo: 60,
      estoqueSeguranca: 15,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 5,
      fotos: JSON.stringify(['/produtos/palheta-1.jpg']),
      imagemPrincipal: '/produtos/palheta-1.jpg',
      descricaoCurta: 'Par de palhetas limpador Bosch Aerotwin. Limpeza silenciosa e eficiente.',
      descricaoCompleta: 'As Palhetas Bosch Aerotwin possuem design aerodinâmico que garante pressão uniforme sobre o vidro, proporcionando limpeza eficiente e silenciosa. Borracha com tratamento especial para maior durabilidade.',
      caracteristicas: JSON.stringify(['Design aerodinâmico', 'Limpeza silenciosa', 'Borracha com grafite', 'Adaptadores universais inclusos']),
      videoUrl: '',
      createdAt: new Date('2024-03-30'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p19',
      nome: 'Coxim do Motor Dianteiro Ford Ranger',
      slug: 'coxim-motor-dianteiro-ford-ranger',
      sku: 'CM-FOR-019',
      codigoOEM: 'AB3941-6F012-AA',
      codigoBarras: '7891234567908',
      ncm: '87082990',
      cest: '0107400',
      referenciaCruzada: JSON.stringify(['0310621', 'EM3122']),
      marca: 'Sampel',
      fabricanteOriginal: 'Ford',
      paisOrigem: 'Brasil',
      tipoAplicacao: 'especifico',
      tipoPeca: 'paralela',
      categoria: 'Motor',
      subcategoria: 'Coxins',
      tags: JSON.stringify(['coxim', 'motor', 'suporte', 'vibração']),
      localizacaoEstoque: 'Prateleira C4 - Caixa 08',
      setorAlmoxarifado: 'Setor C',
      pesoBruto: 2.8,
      pesoLiquido: 2.5,
      comprimento: 18,
      largura: 12,
      altura: 10,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Borracha e metal',
      cor: 'Preto',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 145,
      freteEntrada: 8,
      impostosEntrada: 18,
      custoTotal: 171,
      margemLucro: 38,
      precoVendaSugerido: 235.98,
      precoVendaBalcao: 259.9,
      precoB2B: 229.9,
      precoMinimo: 209.9,
      descontoMaximo: 10,
      precoSite: 249.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 8,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 7,
      estoqueMinimo: 2,
      estoqueMaximo: 15,
      estoqueSeguranca: 4,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f1',
      prazoReposicao: 12,
      fotos: JSON.stringify(['/produtos/coxim-1.jpg']),
      imagemPrincipal: '/produtos/coxim-1.jpg',
      descricaoCurta: 'Coxim do motor dianteiro Sampel para Ford Ranger. Absorção de vibrações.',
      descricaoCompleta: 'O Coxim do Motor Sampel para Ford Ranger é fabricado com borracha de alta resistência e estrutura metálica reforçada. Absorve as vibrações do motor, proporcionando conforto e protegendo os componentes.',
      caracteristicas: JSON.stringify(['Borracha de alta resistência', 'Estrutura metálica reforçada', 'Absorção eficiente de vibrações', 'Para uso em condições severas']),
      videoUrl: '',
      createdAt: new Date('2024-04-01'),
      updatedAt: new Date('2024-04-01'),
    },
    {
      id: 'p20',
      nome: 'Junta do Cabeçote Fiat Fire 1.0/1.4',
      slug: 'junta-cabecote-fiat-fire',
      sku: 'JC-FIA-020',
      codigoOEM: '55210284',
      codigoBarras: '7891234567909',
      ncm: '84841000',
      cest: '0108400',
      referenciaCruzada: JSON.stringify(['61-35090-00', 'AG5640']),
      marca: 'Victor Reinz',
      fabricanteOriginal: 'Fiat',
      paisOrigem: 'Alemanha',
      tipoAplicacao: 'especifico',
      tipoPeca: 'original',
      categoria: 'Motor',
      subcategoria: 'Juntas',
      tags: JSON.stringify(['junta', 'cabeçote', 'vedação', 'motor']),
      localizacaoEstoque: 'Prateleira M2 - Caixa 04',
      setorAlmoxarifado: 'Setor M',
      pesoBruto: 0.25,
      pesoLiquido: 0.2,
      comprimento: 40,
      largura: 20,
      altura: 0.5,
      unidadeMedida: 'UN',
      conteudoEmbalagem: 1,
      material: 'Aço multicamadas com grafite',
      cor: 'Cinza',
      garantia: '12 meses',
      fichaTecnicaUrl: '',
      manualUrl: '',
      custoAquisicao: 185,
      freteEntrada: 8,
      impostosEntrada: 22,
      custoTotal: 215,
      margemLucro: 40,
      precoVendaSugerido: 301,
      precoVendaBalcao: 329.9,
      precoB2B: 289.9,
      precoMinimo: 269.9,
      descontoMaximo: 10,
      precoSite: 319.9,
      precoPromocional: null,
      dataInicioPromocao: null,
      dataFimPromocao: null,
      exibirNoSite: true,
      destaqueHome: false,
      aliquotaICMS: 18,
      aliquotaIPI: 5,
      cstCsosn: '102',
      pisCofins: 3.65,
      regimeTributacao: 'Simples Nacional',
      estoqueAtual: 9,
      estoqueMinimo: 3,
      estoqueMaximo: 20,
      estoqueSeguranca: 5,
      controlaEstoque: true,
      permiteVendaSemEstoque: false,
      fornecedorPadraoId: 'f4',
      prazoReposicao: 10,
      fotos: JSON.stringify(['/produtos/junta-cabecote-1.jpg']),
      imagemPrincipal: '/produtos/junta-cabecote-1.jpg',
      descricaoCurta: 'Junta do cabeçote Victor Reinz para motor Fire Fiat. Vedação perfeita e durável.',
      descricaoCompleta: 'A Junta do Cabeçote Victor Reinz é fabricada em aço multicamadas com revestimento de grafite, oferecendo vedação perfeita entre o bloco e o cabeçote. Projetada para suportar altas temperaturas e pressões.',
      caracteristicas: JSON.stringify(['Tecnologia MLS (Multi Layer Steel)', 'Revestimento de grafite', 'Suporta altas temperaturas', 'Vedação perfeita dos canais']),
      videoUrl: '',
      createdAt: new Date('2024-04-02'),
      updatedAt: new Date('2024-04-02'),
    },
  ];

  for (const p of produtosData) {
    await prisma.produto.create({
      data: p,
    });
  }
  console.log(`Seeded ${produtosData.length} produtos.`);

  // Seed vendasMock
  const vendasMockData = [
    {
      id: 'v1',
      tipoSaida: 'venda_balcao',
      numeroPedido: '1254',
      dataHora: new Date('2024-04-10T14:30:00'),
      cliente: 'José Silva',
      cpfCnpjCliente: '123.456.789-00',
      vendedor: 'Maria Oliveira',
      subtotal: 859.5,
      descontoTotal: 0,
      valorFinal: 859.5,
      formasPagamento: JSON.stringify(['Dinheiro']),
      troco: 40.5,
      observacoes: '',
      emitirNFe: false,
      imprimirCupom: true,
      createdAt: new Date('2024-04-10T14:30:00'),
      itens: {
        create: [
          {
            produtoId: 'p1',
            quantidade: 2,
            unidade: 'UN',
            valorUnitario: 269.8,
            desconto: 0,
            ipi: 0,
            icms: 0,
            valorTotal: 539.6,
          },
          {
            produtoId: 'p5',
            quantidade: 2,
            unidade: 'UN',
            valorUnitario: 159.95,
            desconto: 0,
            ipi: 0,
            icms: 0,
            valorTotal: 319.9,
          },
        ],
      },
    },
  ];

  for (const v of vendasMockData) {
    await prisma.saidaEstoque.create({
      data: v,
    });
  }
  console.log(`Seeded ${vendasMockData.length} vendas.`);

  // Seed gastosMock
  const gastosMockData = [
    {
      id: 'g1',
      descricao: 'Aluguel Loja Abril',
      categoria: 'aluguel',
      valor: 3500,
      dataVencimento: new Date('2024-04-10'),
      dataPagamento: new Date('2024-04-10'),
      formaPagamento: 'TED',
      status: 'pago',
      recorrente: true,
      observacoes: 'Taxa de condomínio incluída.',
      createdAt: new Date('2024-04-01'),
    },
    {
      id: 'g2',
      descricao: 'Salário Maria Oliveira',
      categoria: 'salarios',
      valor: 3200,
      dataVencimento: new Date('2024-04-05'),
      dataPagamento: new Date('2024-04-05'),
      formaPagamento: 'TED',
      status: 'pago',
      recorrente: true,
      observacoes: '',
      createdAt: new Date('2024-04-05'),
    },
  ];

  for (const g of gastosMockData) {
    await prisma.gasto.create({
      data: g,
    });
  }
  console.log(`Seeded ${gastosMockData.length} gastos.`);

  // Seed funcionariosMock
  const funcionariosMockData = [
    {
      id: 'f1',
      nome: 'Maria Oliveira',
      cpf: '123.456.789-00',
      cargo: 'Vendedora',
      setor: 'Vendas',
      telefone: '(11) 98765-4321',
      email: 'maria.oliveira@empresa.com',
      dataAdmissao: new Date('2023-06-15'),
      dataDemissao: null,
      salario: 3200,
      comissaoPercentual: 2.5,
      tipoContrato: 'clt',
      status: 'ativo',
      endereco: 'Rua dos Funcionários, 123, Apt 45, Centro, São Paulo, SP, 01001-000',
      observacoes: 'Excelente vendedora.',
      createdAt: new Date('2023-06-15'),
    },
    {
      id: 'f2',
      nome: 'Carlos Santos',
      cpf: '987.654.321-00',
      cargo: 'Gerente',
      setor: 'Administração',
      telefone: '(11) 91234-5678',
      email: 'carlos.santos@empresa.com',
      dataAdmissao: new Date('2022-03-20'),
      dataDemissao: null,
      salario: 5500,
      comissaoPercentual: 5,
      tipoContrato: 'clt',
      status: 'ativo',
      endereco: 'Av. Paulista, 1000, Conj 101, Bela Vista, São Paulo, SP, 01310-100',
      observacoes: 'Responsável pela equipe.',
      createdAt: new Date('2022-03-20'),
    },
  ];

  for (const f of funcionariosMockData) {
    await prisma.funcionario.create({
      data: f,
    });
  }
  console.log(`Seeded ${funcionariosMockData.length} funcionários.`);

  console.log('Seed completed successfully!');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
