import type { Produto, Fornecedor, EntradaEstoque, SaidaEstoque, DashboardKPIs, MovimentacaoRecente, Gasto, Funcionario } from './types';


// Fornecedores
export const fornecedores: Fornecedor[] = [
  {
    id: 'f1',
    razaoSocial: 'Robert Bosch Ltda',
    nomeFantasia: 'Bosch',
    cnpj: '45.990.181/0001-89',
    inscricaoEstadual: '123.456.789.123',
    contato: 'João Silva',
    telefone: '(11) 4166-8000',
    email: 'comercial@bosch.com.br',
    endereco: {
      logradouro: 'Via Anhanguera',
      numero: 'Km 98',
      complemento: 'Galpão 1',
      bairro: 'Distrito Industrial',
      cidade: 'Campinas',
      estado: 'SP',
      cep: '13065-900'
    },
    dadosBancarios: {
      banco: 'Itaú',
      agencia: '1234',
      conta: '56789-0',
      tipoConta: 'Corrente'
    },
    condicaoPagamentoPadrao: '30/60/90',
    prazoEntrega: 7,
    avaliacao: 5,
    observacoes: 'Fornecedor premium. Entrega sempre no prazo.',
    createdAt: '2024-01-15'
  },
  {
    id: 'f2',
    razaoSocial: 'NGK do Brasil Ltda',
    nomeFantasia: 'NGK',
    cnpj: '47.384.984/0001-01',
    inscricaoEstadual: '456.789.123.456',
    contato: 'Maria Santos',
    telefone: '(11) 2165-8900',
    email: 'vendas@ngk.com.br',
    endereco: {
      logradouro: 'Av. Piraporinha',
      numero: '1950',
      complemento: '',
      bairro: 'Diadema',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '09950-000'
    },
    dadosBancarios: {
      banco: 'Bradesco',
      agencia: '2345',
      conta: '67890-1',
      tipoConta: 'Corrente'
    },
    condicaoPagamentoPadrao: '30 dias',
    prazoEntrega: 5,
    avaliacao: 5,
    observacoes: 'Especialista em velas e sensores.',
    createdAt: '2024-02-10'
  },
  {
    id: 'f3',
    razaoSocial: 'Cofap Amortecedores S/A',
    nomeFantasia: 'Cofap',
    cnpj: '60.476.884/0001-52',
    inscricaoEstadual: '789.123.456.789',
    contato: 'Carlos Oliveira',
    telefone: '(11) 3388-5700',
    email: 'comercial@cofap.com.br',
    endereco: {
      logradouro: 'Av. Industrial',
      numero: '600',
      complemento: 'Bloco B',
      bairro: 'Santo André',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '09080-500'
    },
    dadosBancarios: {
      banco: 'Santander',
      agencia: '3456',
      conta: '78901-2',
      tipoConta: 'Corrente'
    },
    condicaoPagamentoPadrao: '28 dias',
    prazoEntrega: 10,
    avaliacao: 4,
    observacoes: 'Líder em suspensão e amortecedores.',
    createdAt: '2024-01-20'
  },
  {
    id: 'f4',
    razaoSocial: 'Mahle Metal Leve S/A',
    nomeFantasia: 'Mahle',
    cnpj: '60.894.730/0001-05',
    inscricaoEstadual: '321.654.987.321',
    contato: 'Ana Pereira',
    telefone: '(47) 3451-6000',
    email: 'vendas@mahle.com.br',
    endereco: {
      logradouro: 'Rod. BR-280',
      numero: 'Km 50',
      complemento: '',
      bairro: 'Zona Industrial',
      cidade: 'Jaraguá do Sul',
      estado: 'SC',
      cep: '89256-900'
    },
    dadosBancarios: {
      banco: 'Banco do Brasil',
      agencia: '4567',
      conta: '89012-3',
      tipoConta: 'Corrente'
    },
    condicaoPagamentoPadrao: '30/60',
    prazoEntrega: 8,
    avaliacao: 5,
    observacoes: 'Especialista em filtros e pistões.',
    createdAt: '2024-03-05'
  },
  {
    id: 'f5',
    razaoSocial: 'Monroe Amortecedores Ltda',
    nomeFantasia: 'Monroe',
    cnpj: '61.089.062/0001-90',
    inscricaoEstadual: '654.987.321.654',
    contato: 'Roberto Costa',
    telefone: '(11) 4040-5000',
    email: 'pedidos@monroe.com.br',
    endereco: {
      logradouro: 'Av. das Indústrias',
      numero: '2200',
      complemento: 'Galpão 3',
      bairro: 'Guarulhos',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '07220-000'
    },
    dadosBancarios: {
      banco: 'Caixa',
      agencia: '5678',
      conta: '90123-4',
      tipoConta: 'Corrente'
    },
    condicaoPagamentoPadrao: '30 dias',
    prazoEntrega: 6,
    avaliacao: 4,
    observacoes: 'Excelente qualidade em amortecedores.',
    createdAt: '2024-02-25'
  }
];

// Produtos
export const produtos: Produto[] = [
  {
    id: 'p1',
    nome: 'Filtro de Óleo Honda Civic',
    slug: 'filtro-oleo-honda-civic',
    sku: 'FO-HON-001',
    codigoOEM: '15400-PLM-A01',
    codigoBarras: '7891234567890',
    ncm: '84212300',
    cest: '0107800',
    referenciaCruzada: ['PH6017A', 'W610/6'],
    marca: 'Mahle',
    fabricanteOriginal: 'Honda',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v1', montadora: 'Honda', modelo: 'Civic', versaoMotor: '1.8 16V Flex', anoInicial: 2006, anoFinal: 2011, posicao: 'Motor', observacao: '' },
      { id: 'v2', montadora: 'Honda', modelo: 'Civic', versaoMotor: '2.0 16V Flex', anoInicial: 2012, anoFinal: 2016, posicao: 'Motor', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Óleo',
    tags: ['filtro', 'óleo', 'lubrificação', 'motor'],
    localizacaoEstoque: 'Prateleira A3 - Caixa 12',
    setorAlmoxarifado: 'Setor A',
    pesoBruto: 0.35,
    pesoLiquido: 0.30,
    comprimento: 8,
    largura: 8,
    altura: 10,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Metal e papel filtrante',
    cor: 'Preto',
    garantia: '6 meses de fábrica',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 18.50,
    freteEntrada: 1.20,
    impostosEntrada: 2.30,
    custoTotal: 22.00,
    margemLucro: 45,
    precoVendaSugerido: 31.90,
    precoVendaBalcao: 34.90,
    precoB2B: 28.90,
    precoMinimo: 26.00,
    descontoMaximo: 15,
    precoSite: 32.90,
    precoPromocional: 29.90,
    dataInicioPromocao: '2024-04-01',
    dataFimPromocao: '2024-04-30',
    exibirNoSite: true,
    destaqueHome: true,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 45,
    estoqueMinimo: 10,
    estoqueMaximo: 100,
    estoqueSeguranca: 15,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f4',
    prazoReposicao: 5,
    fotos: ['/produtos/filtro-oleo-1.jpg'],
    imagemPrincipal: '/produtos/filtro-oleo-1.jpg',
    descricaoCurta: 'Filtro de óleo de alta qualidade para Honda Civic. Filtragem eficiente e durabilidade garantida.',
    descricaoCompleta: 'O Filtro de Óleo Mahle para Honda Civic oferece filtragem de alta eficiência, removendo partículas e impurezas do óleo do motor. Fabricado com materiais de primeira qualidade, garante proteção máxima ao motor do seu veículo.',
    caracteristicas: ['Filtragem de alta eficiência', 'Material resistente à corrosão', 'Válvula anti-retorno integrada', 'Compatível com óleos sintéticos'],
    videoUrl: '',
    createdAt: '2024-01-15',
    updatedAt: '2024-04-10'
  },
  {
    id: 'p2',
    nome: 'Pastilha de Freio Dianteira VW Golf',
    slug: 'pastilha-freio-dianteira-vw-golf',
    sku: 'PF-VW-002',
    codigoOEM: '1K0698151',
    codigoBarras: '7891234567891',
    ncm: '68131000',
    cest: '0109900',
    referenciaCruzada: ['BP1108', 'P85073'],
    marca: 'Bosch',
    fabricanteOriginal: 'Volkswagen',
    paisOrigem: 'Alemanha',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v3', montadora: 'Volkswagen', modelo: 'Golf', versaoMotor: '1.4 TSI', anoInicial: 2013, anoFinal: null, posicao: 'Dianteiro', observacao: '' },
      { id: 'v4', montadora: 'Volkswagen', modelo: 'Jetta', versaoMotor: '2.0 TSI', anoInicial: 2011, anoFinal: null, posicao: 'Dianteiro', observacao: '' },
      { id: 'v5', montadora: 'Audi', modelo: 'A3', versaoMotor: '1.4 TFSI', anoInicial: 2012, anoFinal: null, posicao: 'Dianteiro', observacao: '' }
    ],
    tipoPeca: 'original',
    categoria: 'Freios',
    subcategoria: 'Pastilhas',
    tags: ['freio', 'pastilha', 'dianteiro', 'segurança'],
    localizacaoEstoque: 'Prateleira B2 - Caixa 08',
    setorAlmoxarifado: 'Setor B',
    pesoBruto: 1.2,
    pesoLiquido: 0.95,
    comprimento: 15,
    largura: 12,
    altura: 5,
    unidadeMedida: 'KIT',
    conteudoEmbalagem: 4,
    material: 'Cerâmica',
    cor: 'Cinza',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 145.00,
    freteEntrada: 8.50,
    impostosEntrada: 18.00,
    custoTotal: 171.50,
    margemLucro: 40,
    precoVendaSugerido: 240.10,
    precoVendaBalcao: 259.90,
    precoB2B: 219.90,
    precoMinimo: 199.90,
    descontoMaximo: 10,
    precoSite: 249.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: true,
    aliquotaICMS: 18,
    aliquotaIPI: 8,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 28,
    estoqueMinimo: 5,
    estoqueMaximo: 50,
    estoqueSeguranca: 8,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 7,
    fotos: ['/produtos/pastilha-freio-1.jpg'],
    imagemPrincipal: '/produtos/pastilha-freio-1.jpg',
    descricaoCurta: 'Kit de pastilhas de freio dianteiras Bosch para VW Golf, Jetta e Audi A3. Frenagem segura e silenciosa.',
    descricaoCompleta: 'As Pastilhas de Freio Bosch são desenvolvidas com tecnologia de ponta, oferecendo frenagem precisa e silenciosa. Composição cerâmica que garante menor desgaste dos discos e maior vida útil do sistema de freios.',
    caracteristicas: ['Tecnologia cerâmica QuietCast', 'Baixa geração de pó', 'Indicador de desgaste', 'Calços anti-ruído inclusos'],
    videoUrl: '',
    createdAt: '2024-01-20',
    updatedAt: '2024-04-08'
  },
  {
    id: 'p3',
    nome: 'Amortecedor Dianteiro Fiat Strada',
    slug: 'amortecedor-dianteiro-fiat-strada',
    sku: 'AM-FIA-003',
    codigoOEM: '51925198',
    codigoBarras: '7891234567892',
    ncm: '87083000',
    cest: '0107100',
    referenciaCruzada: ['41901', 'GP32860'],
    marca: 'Cofap',
    fabricanteOriginal: 'Fiat',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v6', montadora: 'Fiat', modelo: 'Strada', versaoMotor: '1.4 Flex', anoInicial: 2013, anoFinal: null, posicao: 'Dianteiro Esquerdo', observacao: 'Lado motorista' },
      { id: 'v7', montadora: 'Fiat', modelo: 'Palio Weekend', versaoMotor: '1.4/1.8 Flex', anoInicial: 2012, anoFinal: 2017, posicao: 'Dianteiro', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Suspensão',
    subcategoria: 'Amortecedores',
    tags: ['amortecedor', 'suspensão', 'dianteiro', 'conforto'],
    localizacaoEstoque: 'Prateleira C1 - Caixa 01',
    setorAlmoxarifado: 'Setor C',
    pesoBruto: 4.5,
    pesoLiquido: 4.2,
    comprimento: 50,
    largura: 12,
    altura: 12,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Aço e borracha',
    cor: 'Preto/Amarelo',
    garantia: '12 meses ou 20.000 km',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 185.00,
    freteEntrada: 12.00,
    impostosEntrada: 22.00,
    custoTotal: 219.00,
    margemLucro: 35,
    precoVendaSugerido: 295.65,
    precoVendaBalcao: 319.90,
    precoB2B: 279.90,
    precoMinimo: 259.90,
    descontoMaximo: 12,
    precoSite: 309.90,
    precoPromocional: 289.90,
    dataInicioPromocao: '2024-04-05',
    dataFimPromocao: '2024-04-20',
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 10,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 12,
    estoqueMinimo: 4,
    estoqueMaximo: 30,
    estoqueSeguranca: 6,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f3',
    prazoReposicao: 10,
    fotos: ['/produtos/amortecedor-1.jpg'],
    imagemPrincipal: '/produtos/amortecedor-1.jpg',
    descricaoCurta: 'Amortecedor dianteiro Cofap Turbogas para Fiat Strada e Palio Weekend. Conforto e estabilidade.',
    descricaoCompleta: 'O Amortecedor Cofap Turbogas oferece tecnologia de ponta com pressurização de gás nitrogênio, proporcionando resposta mais rápida e precisa da suspensão. Ideal para uso urbano e estradas.',
    caracteristicas: ['Tecnologia Turbogas', 'Pressurização a gás nitrogênio', 'Maior estabilidade em curvas', 'Redução de fadiga do motorista'],
    videoUrl: '',
    createdAt: '2024-02-01',
    updatedAt: '2024-04-05'
  },
  {
    id: 'p4',
    nome: 'Vela de Ignição NGK Iridium',
    slug: 'vela-ignicao-ngk-iridium',
    sku: 'VE-NGK-004',
    codigoOEM: 'ILZKR7B11',
    codigoBarras: '7891234567893',
    ncm: '85111000',
    cest: '0108900',
    referenciaCruzada: ['ZXE16HR11', 'IK16TT'],
    marca: 'NGK',
    fabricanteOriginal: '',
    paisOrigem: 'Japão',
    tipoAplicacao: 'universal',
    veiculosCompativeis: [
      { id: 'v8', montadora: 'Honda', modelo: 'Civic', versaoMotor: '2.0 16V', anoInicial: 2016, anoFinal: null, posicao: 'Todos', observacao: 'Jogo com 4 unidades' },
      { id: 'v9', montadora: 'Toyota', modelo: 'Corolla', versaoMotor: '2.0 16V', anoInicial: 2015, anoFinal: null, posicao: 'Todos', observacao: '' },
      { id: 'v10', montadora: 'Hyundai', modelo: 'HB20', versaoMotor: '1.6 16V', anoInicial: 2012, anoFinal: null, posicao: 'Todos', observacao: '' }
    ],
    tipoPeca: 'original',
    categoria: 'Elétrica',
    subcategoria: 'Velas de Ignição',
    tags: ['vela', 'ignição', 'iridium', 'performance'],
    localizacaoEstoque: 'Prateleira D4 - Caixa 22',
    setorAlmoxarifado: 'Setor D',
    pesoBruto: 0.08,
    pesoLiquido: 0.06,
    comprimento: 3,
    largura: 2,
    altura: 8,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Irídio e platina',
    cor: 'Prata',
    garantia: '24 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 48.00,
    freteEntrada: 2.00,
    impostosEntrada: 6.00,
    custoTotal: 56.00,
    margemLucro: 50,
    precoVendaSugerido: 84.00,
    precoVendaBalcao: 89.90,
    precoB2B: 74.90,
    precoMinimo: 68.00,
    descontoMaximo: 10,
    precoSite: 84.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: true,
    aliquotaICMS: 18,
    aliquotaIPI: 12,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 120,
    estoqueMinimo: 20,
    estoqueMaximo: 200,
    estoqueSeguranca: 30,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f2',
    prazoReposicao: 5,
    fotos: ['/produtos/vela-ngk-1.jpg'],
    imagemPrincipal: '/produtos/vela-ngk-1.jpg',
    descricaoCurta: 'Vela de ignição NGK Iridium de alta performance. Maior durabilidade e eficiência na combustão.',
    descricaoCompleta: 'A Vela de Ignição NGK Iridium é a escolha premium para motores modernos. O eletrodo central de irídio ultrafino proporciona uma faísca mais potente e consistente, resultando em melhor partida, maior economia de combustível e menor emissão de poluentes.',
    caracteristicas: ['Eletrodo central de irídio', 'Durabilidade 4x maior que velas convencionais', 'Melhora partida a frio', 'Economia de combustível de até 5%'],
    videoUrl: '',
    createdAt: '2024-01-25',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p5',
    nome: 'Correia Dentada Gates PowerGrip',
    slug: 'correia-dentada-gates-powergrip',
    sku: 'CO-GAT-005',
    codigoOEM: '5544XS',
    codigoBarras: '7891234567894',
    ncm: '40103900',
    cest: '0100100',
    referenciaCruzada: ['CT909', 'TB909K1'],
    marca: 'Gates',
    fabricanteOriginal: '',
    paisOrigem: 'EUA',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v11', montadora: 'Volkswagen', modelo: 'Gol', versaoMotor: '1.0 8V', anoInicial: 2008, anoFinal: 2016, posicao: 'Motor', observacao: 'G5 e G6' },
      { id: 'v12', montadora: 'Volkswagen', modelo: 'Fox', versaoMotor: '1.0/1.6 8V', anoInicial: 2004, anoFinal: 2014, posicao: 'Motor', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Correia e Corrente',
    subcategoria: 'Correias Dentadas',
    tags: ['correia', 'dentada', 'sincronismo', 'motor'],
    localizacaoEstoque: 'Prateleira E2 - Caixa 15',
    setorAlmoxarifado: 'Setor E',
    pesoBruto: 0.25,
    pesoLiquido: 0.20,
    comprimento: 30,
    largura: 3,
    altura: 3,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Borracha reforçada com fibra de vidro',
    cor: 'Preto',
    garantia: '24 meses ou 40.000 km',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 85.00,
    freteEntrada: 5.00,
    impostosEntrada: 10.00,
    custoTotal: 100.00,
    margemLucro: 45,
    precoVendaSugerido: 145.00,
    precoVendaBalcao: 159.90,
    precoB2B: 139.90,
    precoMinimo: 125.00,
    descontoMaximo: 15,
    precoSite: 149.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 35,
    estoqueMinimo: 8,
    estoqueMaximo: 60,
    estoqueSeguranca: 12,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 7,
    fotos: ['/produtos/correia-1.jpg'],
    imagemPrincipal: '/produtos/correia-1.jpg',
    descricaoCurta: 'Correia dentada Gates PowerGrip para VW Gol e Fox. Sincronismo perfeito e longa durabilidade.',
    descricaoCompleta: 'A Correia Dentada Gates PowerGrip é fabricada com materiais de alta tecnologia que garantem resistência ao desgaste, ao calor e à tração. Mantém o sincronismo perfeito do motor, essencial para o funcionamento correto do veículo.',
    caracteristicas: ['Tecnologia PowerGrip', 'Fibra de vidro de alta resistência', 'Resistente a óleo e calor', 'Troca recomendada a cada 60.000 km'],
    videoUrl: '',
    createdAt: '2024-02-10',
    updatedAt: '2024-03-28'
  },
  {
    id: 'p6',
    nome: 'Bomba de Água GM Chevrolet Onix',
    slug: 'bomba-agua-gm-onix',
    sku: 'BA-GM-006',
    codigoOEM: '24579450',
    codigoBarras: '7891234567895',
    ncm: '84137030',
    cest: '0108200',
    referenciaCruzada: ['FBA0854', 'P981'],
    marca: 'Indisa',
    fabricanteOriginal: 'GM',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v13', montadora: 'Chevrolet', modelo: 'Onix', versaoMotor: '1.0/1.4 Flex', anoInicial: 2012, anoFinal: null, posicao: 'Motor', observacao: '' },
      { id: 'v14', montadora: 'Chevrolet', modelo: 'Prisma', versaoMotor: '1.0/1.4 Flex', anoInicial: 2013, anoFinal: null, posicao: 'Motor', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Arrefecimento',
    subcategoria: 'Bombas de Água',
    tags: ['bomba', 'água', 'arrefecimento', 'motor'],
    localizacaoEstoque: 'Prateleira F3 - Caixa 09',
    setorAlmoxarifado: 'Setor F',
    pesoBruto: 1.8,
    pesoLiquido: 1.5,
    comprimento: 15,
    largura: 12,
    altura: 10,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Alumínio e aço',
    cor: 'Alumínio natural',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 125.00,
    freteEntrada: 8.00,
    impostosEntrada: 15.00,
    custoTotal: 148.00,
    margemLucro: 40,
    precoVendaSugerido: 207.20,
    precoVendaBalcao: 229.90,
    precoB2B: 199.90,
    precoMinimo: 179.90,
    descontoMaximo: 12,
    precoSite: 219.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 8,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 18,
    estoqueMinimo: 5,
    estoqueMaximo: 40,
    estoqueSeguranca: 8,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 8,
    fotos: ['/produtos/bomba-agua-1.jpg'],
    imagemPrincipal: '/produtos/bomba-agua-1.jpg',
    descricaoCurta: 'Bomba de água para GM Onix e Prisma. Circulação eficiente do líquido de arrefecimento.',
    descricaoCompleta: 'A Bomba de Água Indisa para Chevrolet Onix e Prisma é fabricada com componentes de alta qualidade, garantindo a circulação eficiente do líquido de arrefecimento e protegendo o motor contra superaquecimento.',
    caracteristicas: ['Rotor de alta eficiência', 'Rolamento selado de longa vida', 'Junta inclusa na embalagem', 'Testada em bancada'],
    videoUrl: '',
    createdAt: '2024-02-15',
    updatedAt: '2024-03-20'
  },
  {
    id: 'p7',
    nome: 'Kit Embreagem Sachs Fiat Uno',
    slug: 'kit-embreagem-sachs-fiat-uno',
    sku: 'EM-SAC-007',
    codigoOEM: '55190716',
    codigoBarras: '7891234567896',
    ncm: '87089990',
    cest: '0107600',
    referenciaCruzada: ['K1947', '3000951003'],
    marca: 'Sachs',
    fabricanteOriginal: 'Fiat',
    paisOrigem: 'Alemanha',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v15', montadora: 'Fiat', modelo: 'Uno', versaoMotor: '1.0/1.4 Flex', anoInicial: 2010, anoFinal: null, posicao: 'Transmissão', observacao: 'Novo Uno' },
      { id: 'v16', montadora: 'Fiat', modelo: 'Palio', versaoMotor: '1.0/1.4 Flex', anoInicial: 2012, anoFinal: 2017, posicao: 'Transmissão', observacao: '' }
    ],
    tipoPeca: 'original',
    categoria: 'Embreagem',
    subcategoria: 'Kit Completo',
    tags: ['embreagem', 'platô', 'disco', 'rolamento'],
    localizacaoEstoque: 'Prateleira G1 - Caixa 03',
    setorAlmoxarifado: 'Setor G',
    pesoBruto: 5.5,
    pesoLiquido: 5.0,
    comprimento: 30,
    largura: 30,
    altura: 15,
    unidadeMedida: 'KIT',
    conteudoEmbalagem: 3,
    material: 'Aço, ferro fundido e material orgânico',
    cor: 'Preto/Prata',
    garantia: '12 meses sem limite de km',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 420.00,
    freteEntrada: 25.00,
    impostosEntrada: 50.00,
    custoTotal: 495.00,
    margemLucro: 35,
    precoVendaSugerido: 668.25,
    precoVendaBalcao: 699.90,
    precoB2B: 629.90,
    precoMinimo: 589.90,
    descontoMaximo: 10,
    precoSite: 679.90,
    precoPromocional: 649.90,
    dataInicioPromocao: '2024-04-10',
    dataFimPromocao: '2024-04-25',
    exibirNoSite: true,
    destaqueHome: true,
    aliquotaICMS: 18,
    aliquotaIPI: 10,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 8,
    estoqueMinimo: 3,
    estoqueMaximo: 20,
    estoqueSeguranca: 5,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 12,
    fotos: ['/produtos/kit-embreagem-1.jpg'],
    imagemPrincipal: '/produtos/kit-embreagem-1.jpg',
    descricaoCurta: 'Kit de embreagem completo Sachs para Fiat Uno e Palio. Inclui platô, disco e rolamento.',
    descricaoCompleta: 'O Kit de Embreagem Sachs é fornecedor original das principais montadoras e oferece o conjunto completo para troca: platô, disco e rolamento. Fabricado com materiais de alta qualidade para garantir durabilidade e performance.',
    caracteristicas: ['Kit completo (platô + disco + rolamento)', 'Mesma especificação original de fábrica', 'Engrenamento suave e preciso', 'Maior vida útil'],
    videoUrl: '',
    createdAt: '2024-02-20',
    updatedAt: '2024-04-10'
  },
  {
    id: 'p8',
    nome: 'Farol Dianteiro Esquerdo Toyota Corolla',
    slug: 'farol-dianteiro-esquerdo-toyota-corolla',
    sku: 'FA-TOY-008',
    codigoOEM: '81150-02B50',
    codigoBarras: '7891234567897',
    ncm: '85122010',
    cest: '0109100',
    referenciaCruzada: ['TY708L', 'HO2502139'],
    marca: 'Fitam',
    fabricanteOriginal: 'Toyota',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v17', montadora: 'Toyota', modelo: 'Corolla', versaoMotor: '1.8/2.0 16V', anoInicial: 2015, anoFinal: 2019, posicao: 'Dianteiro Esquerdo', observacao: 'Farol com máscara negra' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Iluminação',
    subcategoria: 'Faróis',
    tags: ['farol', 'iluminação', 'dianteiro', 'esquerdo'],
    localizacaoEstoque: 'Prateleira H2 - Caixa 01',
    setorAlmoxarifado: 'Setor H',
    pesoBruto: 3.2,
    pesoLiquido: 2.8,
    comprimento: 50,
    largura: 35,
    altura: 25,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Plástico ABS e policarbonato',
    cor: 'Preto',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 380.00,
    freteEntrada: 22.00,
    impostosEntrada: 45.00,
    custoTotal: 447.00,
    margemLucro: 38,
    precoVendaSugerido: 616.86,
    precoVendaBalcao: 649.90,
    precoB2B: 579.90,
    precoMinimo: 539.90,
    descontoMaximo: 10,
    precoSite: 629.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 8,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 6,
    estoqueMinimo: 2,
    estoqueMaximo: 15,
    estoqueSeguranca: 3,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 15,
    fotos: ['/produtos/farol-corolla-1.jpg'],
    imagemPrincipal: '/produtos/farol-corolla-1.jpg',
    descricaoCurta: 'Farol dianteiro esquerdo para Toyota Corolla 2015-2019. Encaixe perfeito e alta qualidade.',
    descricaoCompleta: 'O Farol Dianteiro Fitam para Toyota Corolla é fabricado seguindo as especificações originais, garantindo encaixe perfeito e iluminação adequada. Lente em policarbonato resistente a impactos e UV.',
    caracteristicas: ['Encaixe original de fábrica', 'Lente em policarbonato UV-resistente', 'Refletor de alta eficiência', 'Não inclui lâmpadas'],
    videoUrl: '',
    createdAt: '2024-03-01',
    updatedAt: '2024-04-02'
  },
  {
    id: 'p9',
    nome: 'Sensor de Rotação VW Polo',
    slug: 'sensor-rotacao-vw-polo',
    sku: 'SE-VW-009',
    codigoOEM: '030906433K',
    codigoBarras: '7891234567898',
    ncm: '90318090',
    cest: '0110100',
    referenciaCruzada: ['V10-72-1050', '0986280408'],
    marca: 'Bosch',
    fabricanteOriginal: 'Volkswagen',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v18', montadora: 'Volkswagen', modelo: 'Polo', versaoMotor: '1.6 MSI', anoInicial: 2018, anoFinal: null, posicao: 'Motor', observacao: '' },
      { id: 'v19', montadora: 'Volkswagen', modelo: 'Virtus', versaoMotor: '1.6 MSI', anoInicial: 2018, anoFinal: null, posicao: 'Motor', observacao: '' }
    ],
    tipoPeca: 'original',
    categoria: 'Elétrica',
    subcategoria: 'Sensores',
    tags: ['sensor', 'rotação', 'injeção', 'eletrônica'],
    localizacaoEstoque: 'Prateleira D2 - Caixa 18',
    setorAlmoxarifado: 'Setor D',
    pesoBruto: 0.15,
    pesoLiquido: 0.12,
    comprimento: 8,
    largura: 3,
    altura: 3,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Plástico e metal',
    cor: 'Preto',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 145.00,
    freteEntrada: 5.00,
    impostosEntrada: 18.00,
    custoTotal: 168.00,
    margemLucro: 42,
    precoVendaSugerido: 238.56,
    precoVendaBalcao: 259.90,
    precoB2B: 229.90,
    precoMinimo: 209.90,
    descontoMaximo: 10,
    precoSite: 249.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 15,
    estoqueMinimo: 4,
    estoqueMaximo: 30,
    estoqueSeguranca: 6,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 7,
    fotos: ['/produtos/sensor-rotacao-1.jpg'],
    imagemPrincipal: '/produtos/sensor-rotacao-1.jpg',
    descricaoCurta: 'Sensor de rotação Bosch para VW Polo e Virtus. Precisão e confiabilidade na leitura.',
    descricaoCompleta: 'O Sensor de Rotação Bosch monitora a velocidade e posição do virabrequim, enviando informações precisas à central eletrônica do motor. Essencial para o funcionamento correto do sistema de injeção e ignição.',
    caracteristicas: ['Fornecedor original VW', 'Alta precisão de leitura', 'Resistente a temperaturas extremas', 'Conector original'],
    videoUrl: '',
    createdAt: '2024-03-05',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p10',
    nome: 'Óleo Motor 5W30 Sintético 1L',
    slug: 'oleo-motor-5w30-sintetico-1l',
    sku: 'OL-MOB-010',
    codigoOEM: '',
    codigoBarras: '7891234567899',
    ncm: '27101932',
    cest: '0601100',
    referenciaCruzada: ['Shell HX8', 'Castrol GTX'],
    marca: 'Mobil',
    fabricanteOriginal: '',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'universal',
    veiculosCompativeis: [],
    tipoPeca: 'original',
    categoria: 'Lubrificantes',
    subcategoria: 'Óleos de Motor',
    tags: ['óleo', 'motor', 'sintético', '5w30', 'lubrificante'],
    localizacaoEstoque: 'Prateleira I1 - Caixa 01',
    setorAlmoxarifado: 'Setor I',
    pesoBruto: 1.0,
    pesoLiquido: 0.9,
    comprimento: 8,
    largura: 8,
    altura: 20,
    unidadeMedida: 'LT',
    conteudoEmbalagem: 1,
    material: 'Óleo sintético',
    cor: 'Âmbar',
    garantia: 'Validade 5 anos',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 32.00,
    freteEntrada: 2.00,
    impostosEntrada: 4.00,
    custoTotal: 38.00,
    margemLucro: 35,
    precoVendaSugerido: 51.30,
    precoVendaBalcao: 54.90,
    precoB2B: 47.90,
    precoMinimo: 44.90,
    descontoMaximo: 10,
    precoSite: 52.90,
    precoPromocional: 49.90,
    dataInicioPromocao: '2024-04-01',
    dataFimPromocao: '2024-04-30',
    exibirNoSite: true,
    destaqueHome: true,
    aliquotaICMS: 25,
    aliquotaIPI: 0,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 85,
    estoqueMinimo: 20,
    estoqueMaximo: 150,
    estoqueSeguranca: 30,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 3,
    fotos: ['/produtos/oleo-motor-1.jpg'],
    imagemPrincipal: '/produtos/oleo-motor-1.jpg',
    descricaoCurta: 'Óleo de motor Mobil 1 5W30 totalmente sintético. Proteção máxima para seu motor.',
    descricaoCompleta: 'O Mobil 1 5W30 é um óleo de motor totalmente sintético que oferece proteção excepcional contra desgaste, depósitos e lamas. Ideal para motores modernos que exigem óleos de baixa viscosidade para melhor economia de combustível.',
    caracteristicas: ['100% sintético', 'Proteção contra desgaste', 'Melhora economia de combustível', 'Partida a frio facilitada'],
    videoUrl: '',
    createdAt: '2024-03-10',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p11',
    nome: 'Bico Injetor Flex Ford Ka',
    slug: 'bico-injetor-flex-ford-ka',
    sku: 'BI-FOR-011',
    codigoOEM: '0280158127',
    codigoBarras: '7891234567900',
    ncm: '84099190',
    cest: '0108100',
    referenciaCruzada: ['IWP143', 'FJ10629'],
    marca: 'Bosch',
    fabricanteOriginal: 'Ford',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v20', montadora: 'Ford', modelo: 'Ka', versaoMotor: '1.0/1.5 Flex', anoInicial: 2014, anoFinal: null, posicao: 'Motor', observacao: '' },
      { id: 'v21', montadora: 'Ford', modelo: 'Ecosport', versaoMotor: '1.5 Flex', anoInicial: 2018, anoFinal: null, posicao: 'Motor', observacao: '' }
    ],
    tipoPeca: 'original',
    categoria: 'Combustível',
    subcategoria: 'Bicos Injetores',
    tags: ['bico', 'injetor', 'combustível', 'flex'],
    localizacaoEstoque: 'Prateleira D5 - Caixa 11',
    setorAlmoxarifado: 'Setor D',
    pesoBruto: 0.08,
    pesoLiquido: 0.06,
    comprimento: 6,
    largura: 2,
    altura: 2,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Metal e plástico',
    cor: 'Preto/Prata',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 165.00,
    freteEntrada: 5.00,
    impostosEntrada: 20.00,
    custoTotal: 190.00,
    margemLucro: 40,
    precoVendaSugerido: 266.00,
    precoVendaBalcao: 289.90,
    precoB2B: 259.90,
    precoMinimo: 239.90,
    descontoMaximo: 10,
    precoSite: 279.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 8,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 22,
    estoqueMinimo: 6,
    estoqueMaximo: 40,
    estoqueSeguranca: 10,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 7,
    fotos: ['/produtos/bico-injetor-1.jpg'],
    imagemPrincipal: '/produtos/bico-injetor-1.jpg',
    descricaoCurta: 'Bico injetor Bosch para Ford Ka e Ecosport Flex. Pulverização precisa do combustível.',
    descricaoCompleta: 'O Bico Injetor Bosch é projetado para sistemas flex, operando com gasolina ou etanol. Oferece pulverização precisa do combustível, garantindo melhor queima e economia.',
    caracteristicas: ['Compatível com etanol e gasolina', 'Pulverização em cone', 'Alta durabilidade', 'Resistente a partículas'],
    videoUrl: '',
    createdAt: '2024-03-12',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p12',
    nome: 'Terminal de Direção Renault Sandero',
    slug: 'terminal-direcao-renault-sandero',
    sku: 'TD-REN-012',
    codigoOEM: '485203446R',
    codigoBarras: '7891234567901',
    ncm: '87089490',
    cest: '0107200',
    referenciaCruzada: ['JTE1116', 'TA2505'],
    marca: 'TRW',
    fabricanteOriginal: 'Renault',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v22', montadora: 'Renault', modelo: 'Sandero', versaoMotor: '1.0/1.6 16V', anoInicial: 2014, anoFinal: null, posicao: 'Dianteiro', observacao: '' },
      { id: 'v23', montadora: 'Renault', modelo: 'Logan', versaoMotor: '1.0/1.6 16V', anoInicial: 2014, anoFinal: null, posicao: 'Dianteiro', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Direção',
    subcategoria: 'Terminais',
    tags: ['terminal', 'direção', 'articulação', 'esterçamento'],
    localizacaoEstoque: 'Prateleira J2 - Caixa 07',
    setorAlmoxarifado: 'Setor J',
    pesoBruto: 0.45,
    pesoLiquido: 0.40,
    comprimento: 15,
    largura: 5,
    altura: 5,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Aço forjado',
    cor: 'Preto',
    garantia: '12 meses ou 20.000 km',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 48.00,
    freteEntrada: 3.00,
    impostosEntrada: 6.00,
    custoTotal: 57.00,
    margemLucro: 45,
    precoVendaSugerido: 82.65,
    precoVendaBalcao: 89.90,
    precoB2B: 79.90,
    precoMinimo: 72.90,
    descontoMaximo: 12,
    precoSite: 85.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 32,
    estoqueMinimo: 8,
    estoqueMaximo: 50,
    estoqueSeguranca: 12,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 6,
    fotos: ['/produtos/terminal-direcao-1.jpg'],
    imagemPrincipal: '/produtos/terminal-direcao-1.jpg',
    descricaoCurta: 'Terminal de direção TRW para Renault Sandero e Logan. Articulação suave e durável.',
    descricaoCompleta: 'O Terminal de Direção TRW é fabricado em aço forjado de alta resistência, com junta esférica de movimentação suave. Essencial para a precisão do sistema de direção.',
    caracteristicas: ['Aço forjado de alta resistência', 'Junta esférica de precisão', 'Guarda-pó de borracha incluso', 'Parafuso e porca de fixação inclusos'],
    videoUrl: '',
    createdAt: '2024-03-15',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p13',
    nome: 'Disco de Freio Dianteiro Hyundai HB20',
    slug: 'disco-freio-dianteiro-hyundai-hb20',
    sku: 'DF-HYU-013',
    codigoOEM: '51712-1S000',
    codigoBarras: '7891234567902',
    ncm: '87083010',
    cest: '0107300',
    referenciaCruzada: ['BD4902', 'DF4426'],
    marca: 'Fremax',
    fabricanteOriginal: 'Hyundai',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v24', montadora: 'Hyundai', modelo: 'HB20', versaoMotor: '1.0/1.6 16V', anoInicial: 2012, anoFinal: null, posicao: 'Dianteiro', observacao: '' },
      { id: 'v25', montadora: 'Hyundai', modelo: 'HB20S', versaoMotor: '1.0/1.6 16V', anoInicial: 2013, anoFinal: null, posicao: 'Dianteiro', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Freios',
    subcategoria: 'Discos',
    tags: ['disco', 'freio', 'dianteiro', 'frenagem'],
    localizacaoEstoque: 'Prateleira B3 - Caixa 02',
    setorAlmoxarifado: 'Setor B',
    pesoBruto: 6.5,
    pesoLiquido: 6.2,
    comprimento: 28,
    largura: 28,
    altura: 5,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Ferro fundido',
    cor: 'Cinza',
    garantia: '12 meses ou 20.000 km',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 78.00,
    freteEntrada: 8.00,
    impostosEntrada: 10.00,
    custoTotal: 96.00,
    margemLucro: 40,
    precoVendaSugerido: 134.40,
    precoVendaBalcao: 149.90,
    precoB2B: 129.90,
    precoMinimo: 119.90,
    descontoMaximo: 12,
    precoSite: 139.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 8,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 14,
    estoqueMinimo: 4,
    estoqueMaximo: 30,
    estoqueSeguranca: 6,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 8,
    fotos: ['/produtos/disco-freio-1.jpg'],
    imagemPrincipal: '/produtos/disco-freio-1.jpg',
    descricaoCurta: 'Disco de freio dianteiro Fremax para Hyundai HB20. Ventilado para melhor dissipação de calor.',
    descricaoCompleta: 'O Disco de Freio Fremax é fabricado em ferro fundido de alta qualidade, com pista de frenagem usinada com precisão. Design ventilado que proporciona melhor dissipação de calor durante a frenagem.',
    caracteristicas: ['Disco ventilado', 'Ferro fundido de alta qualidade', 'Balanceamento de fábrica', 'Tratamento anticorrosivo'],
    videoUrl: '',
    createdAt: '2024-03-18',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p14',
    nome: 'Filtro de Ar Condicionado Universal',
    slug: 'filtro-ar-condicionado-universal',
    sku: 'FA-UNI-014',
    codigoOEM: '',
    codigoBarras: '7891234567903',
    ncm: '84212100',
    cest: '0107900',
    referenciaCruzada: ['CU1827', 'LAK83'],
    marca: 'Mann Filter',
    fabricanteOriginal: '',
    paisOrigem: 'Alemanha',
    tipoAplicacao: 'universal',
    veiculosCompativeis: [],
    tipoPeca: 'paralela',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Ar Condicionado',
    tags: ['filtro', 'cabine', 'ar condicionado', 'pólen'],
    localizacaoEstoque: 'Prateleira A4 - Caixa 20',
    setorAlmoxarifado: 'Setor A',
    pesoBruto: 0.35,
    pesoLiquido: 0.30,
    comprimento: 25,
    largura: 20,
    altura: 3,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Material sintético',
    cor: 'Branco',
    garantia: '6 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 42.00,
    freteEntrada: 3.00,
    impostosEntrada: 5.00,
    custoTotal: 50.00,
    margemLucro: 50,
    precoVendaSugerido: 75.00,
    precoVendaBalcao: 79.90,
    precoB2B: 69.90,
    precoMinimo: 62.90,
    descontoMaximo: 15,
    precoSite: 74.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 48,
    estoqueMinimo: 15,
    estoqueMaximo: 80,
    estoqueSeguranca: 20,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f4',
    prazoReposicao: 5,
    fotos: ['/produtos/filtro-cabine-1.jpg'],
    imagemPrincipal: '/produtos/filtro-cabine-1.jpg',
    descricaoCurta: 'Filtro de ar condicionado Mann Filter com carvão ativado. Purifica o ar da cabine.',
    descricaoCompleta: 'O Filtro de Ar Condicionado Mann Filter com carvão ativado remove pólen, poeira, bactérias e odores desagradáveis do ar que entra na cabine. Proporciona um ambiente mais saudável para os ocupantes.',
    caracteristicas: ['Carvão ativado', 'Retenção de partículas finas', 'Eliminação de odores', 'Troca recomendada a cada 15.000 km'],
    videoUrl: '',
    createdAt: '2024-03-20',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p15',
    nome: 'Radiador de Água Fiat Toro',
    slug: 'radiador-agua-fiat-toro',
    sku: 'RA-FIA-015',
    codigoOEM: '52049155',
    codigoBarras: '7891234567904',
    ncm: '87089100',
    cest: '0108300',
    referenciaCruzada: ['RV3285', 'PA66-GF30'],
    marca: 'Visconde',
    fabricanteOriginal: 'Fiat',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v26', montadora: 'Fiat', modelo: 'Toro', versaoMotor: '1.8/2.0 Flex/Diesel', anoInicial: 2016, anoFinal: null, posicao: 'Dianteiro', observacao: 'Com ar condicionado' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Arrefecimento',
    subcategoria: 'Radiadores',
    tags: ['radiador', 'arrefecimento', 'água', 'motor'],
    localizacaoEstoque: 'Prateleira F1 - Caixa 01',
    setorAlmoxarifado: 'Setor F',
    pesoBruto: 8.5,
    pesoLiquido: 7.8,
    comprimento: 70,
    largura: 50,
    altura: 5,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Alumínio e plástico',
    cor: 'Preto/Alumínio',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 580.00,
    freteEntrada: 35.00,
    impostosEntrada: 70.00,
    custoTotal: 685.00,
    margemLucro: 30,
    precoVendaSugerido: 890.50,
    precoVendaBalcao: 949.90,
    precoB2B: 849.90,
    precoMinimo: 799.90,
    descontoMaximo: 8,
    precoSite: 919.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 10,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 4,
    estoqueMinimo: 2,
    estoqueMaximo: 10,
    estoqueSeguranca: 3,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 15,
    fotos: ['/produtos/radiador-1.jpg'],
    imagemPrincipal: '/produtos/radiador-1.jpg',
    descricaoCurta: 'Radiador de água Visconde para Fiat Toro. Alta capacidade de dissipação térmica.',
    descricaoCompleta: 'O Radiador Visconde para Fiat Toro é fabricado com núcleo de alumínio brazado de alta eficiência e tanques em plástico de engenharia resistente a altas temperaturas. Garante troca térmica superior e longa vida útil.',
    caracteristicas: ['Núcleo de alumínio brazado', 'Tanques em plástico PA66-GF30', 'Alta capacidade de dissipação', 'Testado sob pressão'],
    videoUrl: '',
    createdAt: '2024-03-22',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p16',
    nome: 'Pivô de Suspensão Inferior Chevrolet S10',
    slug: 'pivo-suspensao-inferior-chevrolet-s10',
    sku: 'PI-GM-016',
    codigoOEM: '94728557',
    codigoBarras: '7891234567905',
    ncm: '87089390',
    cest: '0107100',
    referenciaCruzada: ['0220-0049', 'K80566'],
    marca: 'Nakata',
    fabricanteOriginal: 'Chevrolet',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v27', montadora: 'Chevrolet', modelo: 'S10', versaoMotor: '2.4/2.8 Flex/Diesel', anoInicial: 2012, anoFinal: null, posicao: 'Dianteiro Inferior', observacao: '' },
      { id: 'v28', montadora: 'Chevrolet', modelo: 'Trailblazer', versaoMotor: '2.8 Diesel', anoInicial: 2012, anoFinal: null, posicao: 'Dianteiro Inferior', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Suspensão',
    subcategoria: 'Pivôs',
    tags: ['pivô', 'suspensão', 'inferior', 'articulação'],
    localizacaoEstoque: 'Prateleira C3 - Caixa 05',
    setorAlmoxarifado: 'Setor C',
    pesoBruto: 1.2,
    pesoLiquido: 1.0,
    comprimento: 20,
    largura: 8,
    altura: 8,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Aço forjado',
    cor: 'Preto',
    garantia: '12 meses ou 20.000 km',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 95.00,
    freteEntrada: 6.00,
    impostosEntrada: 12.00,
    custoTotal: 113.00,
    margemLucro: 42,
    precoVendaSugerido: 160.46,
    precoVendaBalcao: 179.90,
    precoB2B: 159.90,
    precoMinimo: 145.90,
    descontoMaximo: 10,
    precoSite: 169.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 10,
    estoqueMinimo: 3,
    estoqueMaximo: 20,
    estoqueSeguranca: 5,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f3',
    prazoReposicao: 10,
    fotos: ['/produtos/pivo-1.jpg'],
    imagemPrincipal: '/produtos/pivo-1.jpg',
    descricaoCurta: 'Pivô de suspensão inferior Nakata para S10 e Trailblazer. Resistente para uso severo.',
    descricaoCompleta: 'O Pivô de Suspensão Nakata é fabricado em aço forjado de alta resistência, ideal para veículos utilitários e pick-ups. Junta esférica com guarda-pó de borracha para proteção contra contaminantes.',
    caracteristicas: ['Aço forjado de alta resistência', 'Para uso em condições severas', 'Guarda-pó premium', 'Graxeiro para manutenção'],
    videoUrl: '',
    createdAt: '2024-03-25',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p17',
    nome: 'Bateria Automotiva 60Ah Moura',
    slug: 'bateria-automotiva-60ah-moura',
    sku: 'BA-MOU-017',
    codigoOEM: 'M60GD',
    codigoBarras: '7891234567906',
    ncm: '85071000',
    cest: '0900100',
    referenciaCruzada: ['LB60DD', 'EFB60'],
    marca: 'Moura',
    fabricanteOriginal: '',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'universal',
    veiculosCompativeis: [],
    tipoPeca: 'original',
    categoria: 'Elétrica',
    subcategoria: 'Baterias',
    tags: ['bateria', 'elétrica', '60ah', 'partida'],
    localizacaoEstoque: 'Prateleira K1 - Chão',
    setorAlmoxarifado: 'Setor K',
    pesoBruto: 16.5,
    pesoLiquido: 15.0,
    comprimento: 24,
    largura: 17,
    altura: 18,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Chumbo-ácido',
    cor: 'Preto/Laranja',
    garantia: '18 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 320.00,
    freteEntrada: 15.00,
    impostosEntrada: 40.00,
    custoTotal: 375.00,
    margemLucro: 25,
    precoVendaSugerido: 468.75,
    precoVendaBalcao: 499.90,
    precoB2B: 449.90,
    precoMinimo: 429.90,
    descontoMaximo: 8,
    precoSite: 479.90,
    precoPromocional: 459.90,
    dataInicioPromocao: '2024-04-01',
    dataFimPromocao: '2024-04-15',
    exibirNoSite: true,
    destaqueHome: true,
    aliquotaICMS: 18,
    aliquotaIPI: 0,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 12,
    estoqueMinimo: 4,
    estoqueMaximo: 25,
    estoqueSeguranca: 6,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 5,
    fotos: ['/produtos/bateria-1.jpg'],
    imagemPrincipal: '/produtos/bateria-1.jpg',
    descricaoCurta: 'Bateria automotiva Moura 60Ah. Alta capacidade de partida e durabilidade.',
    descricaoCompleta: 'A Bateria Moura 60Ah é líder no mercado brasileiro, oferecendo alta capacidade de partida mesmo em condições extremas. Tecnologia selada livre de manutenção com indicador de carga.',
    caracteristicas: ['Selada livre de manutenção', 'Indicador de carga', 'Alta capacidade de partida a frio', 'Caixa sucateada: R$ 50,00 de bônus'],
    videoUrl: '',
    createdAt: '2024-03-28',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p18',
    nome: 'Palheta Limpador Parabrisa Par',
    slug: 'palheta-limpador-parabrisa-par',
    sku: 'PA-BOS-018',
    codigoOEM: '',
    codigoBarras: '7891234567907',
    ncm: '85129090',
    cest: '0109500',
    referenciaCruzada: ['AP24U/AP18U', '3397007523'],
    marca: 'Bosch',
    fabricanteOriginal: '',
    paisOrigem: 'Alemanha',
    tipoAplicacao: 'universal',
    veiculosCompativeis: [],
    tipoPeca: 'original',
    categoria: 'Acessórios',
    subcategoria: 'Limpadores',
    tags: ['palheta', 'limpador', 'parabrisa', 'borracha'],
    localizacaoEstoque: 'Prateleira L2 - Caixa 12',
    setorAlmoxarifado: 'Setor L',
    pesoBruto: 0.35,
    pesoLiquido: 0.30,
    comprimento: 60,
    largura: 5,
    altura: 3,
    unidadeMedida: 'PAR',
    conteudoEmbalagem: 2,
    material: 'Plástico e borracha',
    cor: 'Preto',
    garantia: '6 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 58.00,
    freteEntrada: 4.00,
    impostosEntrada: 7.00,
    custoTotal: 69.00,
    margemLucro: 40,
    precoVendaSugerido: 96.60,
    precoVendaBalcao: 109.90,
    precoB2B: 94.90,
    precoMinimo: 86.90,
    descontoMaximo: 12,
    precoSite: 99.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 35,
    estoqueMinimo: 10,
    estoqueMaximo: 60,
    estoqueSeguranca: 15,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 5,
    fotos: ['/produtos/palheta-1.jpg'],
    imagemPrincipal: '/produtos/palheta-1.jpg',
    descricaoCurta: 'Par de palhetas limpador Bosch Aerotwin. Limpeza silenciosa e eficiente.',
    descricaoCompleta: 'As Palhetas Bosch Aerotwin possuem design aerodinâmico que garante pressão uniforme sobre o vidro, proporcionando limpeza eficiente e silenciosa. Borracha com tratamento especial para maior durabilidade.',
    caracteristicas: ['Design aerodinâmico', 'Limpeza silenciosa', 'Borracha com grafite', 'Adaptadores universais inclusos'],
    videoUrl: '',
    createdAt: '2024-03-30',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p19',
    nome: 'Coxim do Motor Dianteiro Ford Ranger',
    slug: 'coxim-motor-dianteiro-ford-ranger',
    sku: 'CM-FOR-019',
    codigoOEM: 'AB3941-6F012-AA',
    codigoBarras: '7891234567908',
    ncm: '87082990',
    cest: '0107400',
    referenciaCruzada: ['0310621', 'EM3122'],
    marca: 'Sampel',
    fabricanteOriginal: 'Ford',
    paisOrigem: 'Brasil',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v29', montadora: 'Ford', modelo: 'Ranger', versaoMotor: '2.2/3.2 Diesel', anoInicial: 2012, anoFinal: null, posicao: 'Dianteiro Motor', observacao: '' }
    ],
    tipoPeca: 'paralela',
    categoria: 'Motor',
    subcategoria: 'Coxins',
    tags: ['coxim', 'motor', 'suporte', 'vibração'],
    localizacaoEstoque: 'Prateleira C4 - Caixa 08',
    setorAlmoxarifado: 'Setor C',
    pesoBruto: 2.8,
    pesoLiquido: 2.5,
    comprimento: 18,
    largura: 12,
    altura: 10,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Borracha e metal',
    cor: 'Preto',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 145.00,
    freteEntrada: 8.00,
    impostosEntrada: 18.00,
    custoTotal: 171.00,
    margemLucro: 38,
    precoVendaSugerido: 235.98,
    precoVendaBalcao: 259.90,
    precoB2B: 229.90,
    precoMinimo: 209.90,
    descontoMaximo: 10,
    precoSite: 249.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 8,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 7,
    estoqueMinimo: 2,
    estoqueMaximo: 15,
    estoqueSeguranca: 4,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f1',
    prazoReposicao: 12,
    fotos: ['/produtos/coxim-1.jpg'],
    imagemPrincipal: '/produtos/coxim-1.jpg',
    descricaoCurta: 'Coxim do motor dianteiro Sampel para Ford Ranger. Absorção de vibrações.',
    descricaoCompleta: 'O Coxim do Motor Sampel para Ford Ranger é fabricado com borracha de alta resistência e estrutura metálica reforçada. Absorve as vibrações do motor, proporcionando conforto e protegendo os componentes.',
    caracteristicas: ['Borracha de alta resistência', 'Estrutura metálica reforçada', 'Absorção eficiente de vibrações', 'Para uso em condições severas'],
    videoUrl: '',
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01'
  },
  {
    id: 'p20',
    nome: 'Junta do Cabeçote Fiat Fire 1.0/1.4',
    slug: 'junta-cabecote-fiat-fire',
    sku: 'JC-FIA-020',
    codigoOEM: '55210284',
    codigoBarras: '7891234567909',
    ncm: '84841000',
    cest: '0108400',
    referenciaCruzada: ['61-35090-00', 'AG5640'],
    marca: 'Victor Reinz',
    fabricanteOriginal: 'Fiat',
    paisOrigem: 'Alemanha',
    tipoAplicacao: 'especifico',
    veiculosCompativeis: [
      { id: 'v30', montadora: 'Fiat', modelo: 'Uno', versaoMotor: '1.0/1.4 Fire Flex', anoInicial: 2004, anoFinal: null, posicao: 'Motor', observacao: '' },
      { id: 'v31', montadora: 'Fiat', modelo: 'Palio', versaoMotor: '1.0/1.4 Fire Flex', anoInicial: 2004, anoFinal: null, posicao: 'Motor', observacao: '' },
      { id: 'v32', montadora: 'Fiat', modelo: 'Siena', versaoMotor: '1.0/1.4 Fire Flex', anoInicial: 2004, anoFinal: null, posicao: 'Motor', observacao: '' }
    ],
    tipoPeca: 'original',
    categoria: 'Motor',
    subcategoria: 'Juntas',
    tags: ['junta', 'cabeçote', 'vedação', 'motor'],
    localizacaoEstoque: 'Prateleira M2 - Caixa 04',
    setorAlmoxarifado: 'Setor M',
    pesoBruto: 0.25,
    pesoLiquido: 0.20,
    comprimento: 40,
    largura: 20,
    altura: 0.5,
    unidadeMedida: 'UN',
    conteudoEmbalagem: 1,
    material: 'Aço multicamadas com grafite',
    cor: 'Cinza',
    garantia: '12 meses',
    fichaTecnicaUrl: '',
    manualUrl: '',
    custoAquisicao: 185.00,
    freteEntrada: 8.00,
    impostosEntrada: 22.00,
    custoTotal: 215.00,
    margemLucro: 40,
    precoVendaSugerido: 301.00,
    precoVendaBalcao: 329.90,
    precoB2B: 289.90,
    precoMinimo: 269.90,
    descontoMaximo: 10,
    precoSite: 319.90,
    precoPromocional: null,
    dataInicioPromocao: null,
    dataFimPromocao: null,
    exibirNoSite: true,
    destaqueHome: false,
    aliquotaICMS: 18,
    aliquotaIPI: 5,
    cstCsosn: '102',
    pisCofins: 3.65,
    regimeTributacao: 'Simples Nacional',
    estoqueAtual: 9,
    estoqueMinimo: 3,
    estoqueMaximo: 20,
    estoqueSeguranca: 5,
    controlaEstoque: true,
    permiteVendaSemEstoque: false,
    fornecedorPadraoId: 'f4',
    prazoReposicao: 10,
    fotos: ['/produtos/junta-cabecote-1.jpg'],
    imagemPrincipal: '/produtos/junta-cabecote-1.jpg',
    descricaoCurta: 'Junta do cabeçote Victor Reinz para motor Fire Fiat. Vedação perfeita e durável.',
    descricaoCompleta: 'A Junta do Cabeçote Victor Reinz é fabricada em aço multicamadas com revestimento de grafite, oferecendo vedação perfeita entre o bloco e o cabeçote. Projetada para suportar altas temperaturas e pressões.',
    caracteristicas: ['Tecnologia MLS (Multi Layer Steel)', 'Revestimento de grafite', 'Suporta altas temperaturas', 'Vedação perfeita dos canais'],
    videoUrl: '',
    createdAt: '2024-04-02',
    updatedAt: '2024-04-02'
  }
];

// KPIs do Dashboard
export const dashboardKPIs: DashboardKPIs = {
  vendasHoje: 3450.80,
  pedidosHoje: 12,
  vendasMes: 78540.60,
  variacaoMes: 12.5,
  ticketMedio: 287.50,
  produtosEmFalta: 3,
  contasAPagar: 15680.00,
  cmvMes: 48250.00,
  margemBruta: 38.5
};

// Movimentações recentes
export const movimentacoesRecentes: MovimentacaoRecente[] = [
  { id: 'm1', tipo: 'saida', descricao: 'Venda Balcão #1254', quantidade: 4, valor: 539.60, data: '2024-04-10T14:30:00', status: 'concluido' },
  { id: 'm2', tipo: 'entrada', descricao: 'NF 45892 - Bosch', quantidade: 50, valor: 2450.00, data: '2024-04-10T11:15:00', status: 'concluido' },
  { id: 'm3', tipo: 'saida', descricao: 'Venda Online #8832', quantidade: 2, valor: 659.80, data: '2024-04-10T09:45:00', status: 'concluido' },
  { id: 'm4', tipo: 'saida', descricao: 'Venda Balcão #1253', quantidade: 1, valor: 319.90, data: '2024-04-09T17:20:00', status: 'concluido' },
  { id: 'm5', tipo: 'entrada', descricao: 'NF 78432 - NGK', quantidade: 100, valor: 4800.00, data: '2024-04-09T14:00:00', status: 'concluido' },
  { id: 'm6', tipo: 'saida', descricao: 'Devolução Fornecedor', quantidade: 5, valor: 245.00, data: '2024-04-09T10:30:00', status: 'pendente' },
  { id: 'm7', tipo: 'saida', descricao: 'Venda B2B #445', quantidade: 15, valor: 1348.50, data: '2024-04-08T16:45:00', status: 'concluido' },
  { id: 'm8', tipo: 'entrada', descricao: 'NF 12098 - Cofap', quantidade: 20, valor: 4380.00, data: '2024-04-08T11:00:00', status: 'concluido' },
  { id: 'm9', tipo: 'saida', descricao: 'Venda Balcão #1252', quantidade: 3, valor: 447.70, data: '2024-04-08T09:15:00', status: 'concluido' },
  { id: 'm10', tipo: 'saida', descricao: 'Ajuste Inventário', quantidade: 2, valor: 0, data: '2024-04-07T18:00:00', status: 'concluido' }
];

// Dados para gráficos
export const vendasUltimos30Dias = [
  { data: '11/03', valor: 2450 },
  { data: '12/03', valor: 3120 },
  { data: '13/03', valor: 2890 },
  { data: '14/03', valor: 3450 },
  { data: '15/03', valor: 4200 },
  { data: '16/03', valor: 3800 },
  { data: '17/03', valor: 1200 },
  { data: '18/03', valor: 2650 },
  { data: '19/03', valor: 3100 },
  { data: '20/03', valor: 2980 },
  { data: '21/03', valor: 3560 },
  { data: '22/03', valor: 4100 },
  { data: '23/03', valor: 3750 },
  { data: '24/03', valor: 1450 },
  { data: '25/03', valor: 2800 },
  { data: '26/03', valor: 3200 },
  { data: '27/03', valor: 2950 },
  { data: '28/03', valor: 3680 },
  { data: '29/03', valor: 4350 },
  { data: '30/03', valor: 3900 },
  { data: '31/03', valor: 1600 },
  { data: '01/04', valor: 2750 },
  { data: '02/04', valor: 3050 },
  { data: '03/04', valor: 2880 },
  { data: '04/04', valor: 3420 },
  { data: '05/04', valor: 4500 },
  { data: '06/04', valor: 3650 },
  { data: '07/04', valor: 1380 },
  { data: '08/04', valor: 2920 },
  { data: '09/04', valor: 3180 },
  { data: '10/04', valor: 3450 }
];

export const topProdutosMes = [
  { nome: 'Óleo Motor 5W30', quantidade: 85, valor: 4241.50 },
  { nome: 'Vela NGK Iridium', quantidade: 68, valor: 5753.20 },
  { nome: 'Filtro de Óleo', quantidade: 52, valor: 1554.80 },
  { nome: 'Pastilha Freio Bosch', quantidade: 28, valor: 6877.20 },
  { nome: 'Palheta Limpador', quantidade: 25, valor: 2497.50 },
  { nome: 'Correia Dentada', quantidade: 22, valor: 3297.80 },
  { nome: 'Amortecedor Cofap', quantidade: 18, valor: 5218.20 },
  { nome: 'Filtro Ar Cond.', quantidade: 16, valor: 1198.40 },
  { nome: 'Terminal Direção', quantidade: 14, valor: 1202.60 },
  { nome: 'Bateria Moura 60Ah', quantidade: 8, valor: 3679.20 }
];

export const vendasPorCategoria = [
  { categoria: 'Filtros', valor: 8540, cor: '#F97316' },
  { categoria: 'Freios', valor: 12350, cor: '#22C55E' },
  { categoria: 'Suspensão', valor: 9870, cor: '#3B82F6' },
  { categoria: 'Elétrica', valor: 15420, cor: '#EAB308' },
  { categoria: 'Motor', valor: 11280, cor: '#8B5CF6' },
  { categoria: 'Outros', valor: 21080, cor: '#6B7280' }
];

// Categorias disponíveis
export const categorias = [
  { id: 'motor', nome: 'Motor', subcategorias: ['Pistões', 'Anéis', 'Bronzinas', 'Juntas', 'Coxins', 'Válvulas'] },
  { id: 'freios', nome: 'Freios', subcategorias: ['Pastilhas', 'Discos', 'Tambores', 'Lonas', 'Cilindros', 'Flexíveis'] },
  { id: 'suspensao', nome: 'Suspensão', subcategorias: ['Amortecedores', 'Molas', 'Pivôs', 'Buchas', 'Bandejas', 'Bieletas'] },
  { id: 'transmissao', nome: 'Transmissão', subcategorias: ['Kits Embreagem', 'Rolamentos', 'Câmbio', 'Juntas Homocinéticas'] },
  { id: 'eletrica', nome: 'Elétrica', subcategorias: ['Velas de Ignição', 'Sensores', 'Baterias', 'Alternadores', 'Motores de Partida', 'Bobinas'] },
  { id: 'filtros', nome: 'Filtros', subcategorias: ['Filtro de Óleo', 'Filtro de Ar', 'Filtro de Combustível', 'Filtro de Ar Condicionado'] },
  { id: 'correia', nome: 'Correia e Corrente', subcategorias: ['Correias Dentadas', 'Correias Poly-V', 'Kits de Correia', 'Correntes de Comando'] },
  { id: 'arrefecimento', nome: 'Arrefecimento', subcategorias: ['Radiadores', 'Bombas de Água', 'Válvulas Termostáticas', 'Mangueiras', 'Ventoinhas'] },
  { id: 'combustivel', nome: 'Combustível', subcategorias: ['Bicos Injetores', 'Bombas de Combustível', 'Filtros', 'Reguladores de Pressão'] },
  { id: 'escapamento', nome: 'Escapamento', subcategorias: ['Catalisadores', 'Silenciosos', 'Flexíveis', 'Abraçadeiras'] },
  { id: 'carroceria', nome: 'Carroceria', subcategorias: ['Para-choques', 'Capôs', 'Para-lamas', 'Retrovisores'] },
  { id: 'acessorios', nome: 'Acessórios', subcategorias: ['Limpadores', 'Tapetes', 'Capas', 'Organizadores'] },
  { id: 'embreagem', nome: 'Embreagem', subcategorias: ['Kit Completo', 'Platôs', 'Discos', 'Rolamentos'] },
  { id: 'direcao', nome: 'Direção', subcategorias: ['Terminais', 'Barras', 'Caixas', 'Bombas'] },
  { id: 'iluminacao', nome: 'Iluminação', subcategorias: ['Faróis', 'Lanternas', 'Lâmpadas', 'LEDs'] },
  { id: 'lubrificantes', nome: 'Lubrificantes', subcategorias: ['Óleos de Motor', 'Óleos de Câmbio', 'Fluidos de Freio', 'Aditivos'] }
];

// Marcas disponíveis
export const marcas = [
  'Bosch', 'NGK', 'Cofap', 'Mahle', 'Monroe', 'Gates', 'Sachs', 'TRW', 
  'Fremax', 'Mann Filter', 'Indisa', 'Nakata', 'Moura', 'Visconde', 
  'Sampel', 'Victor Reinz', 'Fitam', 'Mobil', 'Shell', 'Castrol'
];

// Montadoras disponíveis
export const montadoras = [
  { nome: 'Fiat', modelos: ['Uno', 'Palio', 'Siena', 'Strada', 'Toro', 'Mobi', 'Argo', 'Cronos'] },
  { nome: 'Volkswagen', modelos: ['Gol', 'Fox', 'Polo', 'Virtus', 'Golf', 'Jetta', 'T-Cross', 'Nivus'] },
  { nome: 'Chevrolet', modelos: ['Onix', 'Prisma', 'Cruze', 'Tracker', 'S10', 'Trailblazer', 'Spin', 'Cobalt'] },
  { nome: 'Ford', modelos: ['Ka', 'Ecosport', 'Ranger', 'Fiesta', 'Focus', 'Fusion', 'Territory'] },
  { nome: 'Honda', modelos: ['Civic', 'City', 'Fit', 'HR-V', 'CR-V', 'WR-V', 'Accord'] },
  { nome: 'Toyota', modelos: ['Corolla', 'Yaris', 'Hilux', 'SW4', 'Etios', 'RAV4', 'Camry'] },
  { nome: 'Hyundai', modelos: ['HB20', 'HB20S', 'Creta', 'Tucson', 'Santa Fe', 'i30', 'Azera'] },
  { nome: 'Renault', modelos: ['Sandero', 'Logan', 'Kwid', 'Duster', 'Captur', 'Oroch', 'Master'] },
  { nome: 'Nissan', modelos: ['March', 'Versa', 'Sentra', 'Kicks', 'Frontier', 'Leaf'] },
  { nome: 'Jeep', modelos: ['Renegade', 'Compass', 'Commander', 'Wrangler', 'Gladiator'] },
  { nome: 'Audi', modelos: ['A3', 'A4', 'A5', 'Q3', 'Q5', 'Q7', 'TT'] },
  { nome: 'BMW', modelos: ['Série 1', 'Série 3', 'Série 5', 'X1', 'X3', 'X5', 'X6'] },
  { nome: 'Mercedes-Benz', modelos: ['Classe A', 'Classe C', 'Classe E', 'GLA', 'GLC', 'GLE'] }
];


// Mock de Carrinho
export const carrinhoMock: { produto: Produto, quantidade: number }[] = [
  {
    produto: produtos[0], // Filtro de Óleo
    quantidade: 2
  },
  {
    produto: produtos[1], // Pastilha de Freio
    quantidade: 1
  },
  {
    produto: produtos[3], // Vela de Ignição
    quantidade: 4
  }
];
